### ISSUE TITLE
Missing dll files

### ISSUE THREAD

**Issue by char101** [TianZerL/Anime4KCPP#1]
Hi,

The release archive is missing these dll files

```
libgcc_s_seh-1.dll
libstdc++-6.dll
libwinpthread-1.dll
```

Thanks.

**Comment by TianZerL** [comment]
Well, it is my fault, I forgot to add the mingw64 runtime to the release archive. Please download the newest release archive.

**Comment by TianZerL** [comment]
I will close this issue, if you have any other issue, feel free to open a new issue.

**Comment by char101** [comment]
Thanks, I had found the DLLs by searching my hard drive so I haven't tested the new release.
