### ISSUE TITLE
Anime4KCPP 使用时资源占用很低

### ISSUE THREAD

**Issue by BlueSkyXN** [TianZerL/Anime4KCPP#103]
作者您好，我在使用Anime4KCPP时发现，进行视频处理时系统占用一直处于较低的状态
CPU占用在整体25%左右波动，GPU在0-50%来回跳动
仔细观察发现：我的CPU，i7-13700kf是8大核8小核设计，视频处理时8小核出现明显负载，8大核中差不多只有2-3个在干点活，而且全部核心使用率波动还挺大的，可以如下图所示
对于软件设置，我将线程数拉到了99线程，占用还是这样，占用低，性能没有吃满

![QQ图片20230122190402](https://user-images.githubusercontent.com/63384277/213912536-328dc00c-1da2-4ea8-b3bf-484a70028bc8.png)
[](url)
![QQ图片20230122190156](https://user-images.githubusercontent.com/63384277/213912494-31add754-e70a-4b95-a50c-5847088543f9.png)
![QQ图片20230122190440](https://user-images.githubusercontent.com/63384277/213912561-ca9d6615-c454-4b8d-bb4e-e73992fc3f3e.png)

**Comment by TianZerL** [comment]
N卡应该在任务管理器检查CUDA使用率
