### ISSUE TITLE
Vapoursynth output has some problems

### ISSUE THREAD

**Issue by theChaosCoder** [TianZerL/Anime4KCPP#11]
VSR50, win10 x64, Ryzen 2600, GTX 1070
On the right side is always a border with strange output
```
clip = 480p DVD ntsc source
clip = mvf.ToRGB(clip)
clip = core.anime4kcpp.Anime4KCPP(clip,zoomFactor=2, GPUMode = 1)
```
![image](https://user-images.githubusercontent.com/3579830/82118486-1147a880-9778-11ea-81ae-c99f76fa2835.png)

**Comment by theChaosCoder** [comment]
Oh and the size is  1472x960. Not 1440x960! 32px from hell :D

**Comment by TianZerL** [comment]
VapourSynth required the width of the video must be multiple of 32, so I need to resize it to 1472x960 instead of 1440x960, you can cut it manually, or you can set output stream to YUV444, this will make the extra 32px to be black.

**Comment by theChaosCoder** [comment]
But 1440 / 32 = 45 ...

**Comment by TianZerL** [comment]
But 720 not, you know.

**Comment by theChaosCoder** [comment]
I see, so I just cut it off and everything is good.

**Comment by TianZerL** [comment]
720/32 = 22.5, 23*32*2 = 1472, this is where the 32px from. 😀

**Comment by theChaosCoder** [comment]
I will just ask here: Only  RGB24 is supported? Because RGB30+ looks very weird. Maybe an error msg would be better instead of showing the output.

**Comment by TianZerL** [comment]
The Anime4KCPP libs is designed for 8bit RGB image, the alpha channel will be ignore. so if your tried to input a video which is more than 24bit per pixel, you may get a weird output. I didn't tried it actually.

**Comment by TianZerL** [comment]
BTW, what do you mean `Maybe an error msg would be better instead of showing the output.`, you will get a error msg, won't you?

**Comment by TianZerL** [comment]
I just tried to input a RGB48 video stream (16bit for each R, G and B channel), it looks very wired, blurred screen.

**Comment by theChaosCoder** [comment]
Yes and that should not be allowed, only RGB24.

**Comment by TianZerL** [comment]
Thanks for your suggestion, I have added a more detailed checking of RGB24, and give an error msg.

**Comment by TianZerL** [comment]
The problem has been completely solved in newest version.
