### ISSUE TITLE
将 Anime4KCPP_Android 用于视频上，出现 crash，您帮忙看下

### ISSUE THREAD

**Issue by liguobing** [TianZerL/Anime4KCPP#113]
因为这个库处理速度实在是太快了，所以我想要将它应用到实时视频上

具体操作是，获取到视频每一帧的 Bitmap，然后存在一个 queue 中，然后再另一个线程中从 queue 去数据，交由 Anime4KCPP 处理，得到新的 Bitmap，再渲染到一个 Bitmap 上

经常在处理了300-400个 bitmap 后出现 crash，具体报错如下：

```
A  Cmdline: github.tianzerl.anime4kcpp
A  pid: 28351, tid: 28409, name: Thread-3  >>> github.tianzerl.anime4kcpp <<<
A        #00 pc 00000000000b323c  /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!libc++_shared.so (BuildId: 67e966ac77ca70ae9867f54c3711ee9a6c96e3b6)
A        #01 pc 00000000000b41e4  /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!libc++_shared.so (BuildId: 67e966ac77ca70ae9867f54c3711ee9a6c96e3b6)
A        #02 pc 00000000000ae050  /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!libc++_shared.so (__cxa_throw+104) (BuildId: 67e966ac77ca70ae9867f54c3711ee9a6c96e3b6)
A        #03 pc 000000000013f500  /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!libAnime4KCPPCore.so (Anime4KCPP::OpenCL::Anime4K09::runKernel(cv::Mat const&, cv::Mat&, int)+3120) (BuildId: 4fe105cdc76f648093e878ef6f2e817ec4055ad3)
A        #04 pc 000000000013c588  /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!libAnime4KCPPCore.so (Anime4KCPP::OpenCL::Anime4K09::runKernelB(cv::Mat const&, cv::Mat&)+40) (BuildId: 4fe105cdc76f648093e878ef6f2e817ec4055ad3)
A        #05 pc 000000000013c770  /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!libAnime4KCPPCore.so (Anime4KCPP::OpenCL::Anime4K09::processRGBImageB()+472) (BuildId: 4fe105cdc76f648093e878ef6f2e817ec4055ad3)
A        #06 pc 00000000000f0b2c  /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!libAnime4KCPPCore.so (Anime4KCPP::AC::process()+184) (BuildId: 4fe105cdc76f648093e878ef6f2e817ec4055ad3)
A        #07 pc 00000000000e22ec  /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!libAnime4KCPPCore.so (Java_github_tianzerl_anime4kcpp_wrapper_Anime4K_processAnime4K+32) (BuildId: 4fe105cdc76f648093e878ef6f2e817ec4055ad3)
A        #10 pc 0000000000000e5c  [anon:dalvik-classes5.dex extracted in memory from /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!classes5.dex] (github.tianzerl.anime4kcpp.wrapper.Anime4K.process+4)
A        #12 pc 00000000000021fc  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!classes4.dex] (github.tianzerl.anime4kcpp.Anime4KCPPUtil.reSizeBitmap+8)
A        #14 pc 0000000000004a64  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!classes4.dex] (github.tianzerl.anime4kcpp.TestActivity.lambda$processImage$2$github-tianzerl-anime4kcpp-TestActivity+124)
A        #16 pc 0000000000004700  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!classes4.dex] (github.tianzerl.anime4kcpp.TestActivity$$ExternalSyntheticLambda4.run+4)
2023-11-28 17:30:52.844 28351-28367 BLASTBufferQueue        github.tianzerl.anime4kcpp           E  [VRI[TestActivity]#0](f:0,a:2) Faking releaseBufferCallback from transactionCompleteCallback
---------------------------- PROCESS ENDED (28351) for package github.tianzerl.anime4kcpp ----------------------------

```

想请教您，该从哪方面入手处理啊

**Comment by TianZerL** [comment]
是不是爆内存或者显存被系统kill掉了，注意控制队列大小，平衡io速度和处理速度。
看函数是崩溃在了OpenCL的处理函数上，这一步会提交数据给OpenCL，如果你开太多线程的话，就会塞很多数据给GPU。

**Comment by CoderCaiSL** [comment]
> 因为这个库处理速度实在是太快了，所以我想要将它应用到实时视频上
> 
> 具体操作是，获取到视频每一帧的 Bitmap，然后存在一个 queue 中，然后再另一个线程中从 queue 去数据，交由 Anime4KCPP 处理，得到新的 Bitmap，再渲染到一个 Bitmap 上
> 
> 经常在处理了300-400个 bitmap 后出现 crash，具体报错如下：
> 
> ```
> A  Cmdline: github.tianzerl.anime4kcpp
> A  pid: 28351, tid: 28409, name: Thread-3  >>> github.tianzerl.anime4kcpp <<<
> A        #00 pc 00000000000b323c  /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!libc++_shared.so (BuildId: 67e966ac77ca70ae9867f54c3711ee9a6c96e3b6)
> A        #01 pc 00000000000b41e4  /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!libc++_shared.so (BuildId: 67e966ac77ca70ae9867f54c3711ee9a6c96e3b6)
> A        #02 pc 00000000000ae050  /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!libc++_shared.so (__cxa_throw+104) (BuildId: 67e966ac77ca70ae9867f54c3711ee9a6c96e3b6)
> A        #03 pc 000000000013f500  /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!libAnime4KCPPCore.so (Anime4KCPP::OpenCL::Anime4K09::runKernel(cv::Mat const&, cv::Mat&, int)+3120) (BuildId: 4fe105cdc76f648093e878ef6f2e817ec4055ad3)
> A        #04 pc 000000000013c588  /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!libAnime4KCPPCore.so (Anime4KCPP::OpenCL::Anime4K09::runKernelB(cv::Mat const&, cv::Mat&)+40) (BuildId: 4fe105cdc76f648093e878ef6f2e817ec4055ad3)
> A        #05 pc 000000000013c770  /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!libAnime4KCPPCore.so (Anime4KCPP::OpenCL::Anime4K09::processRGBImageB()+472) (BuildId: 4fe105cdc76f648093e878ef6f2e817ec4055ad3)
> A        #06 pc 00000000000f0b2c  /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!libAnime4KCPPCore.so (Anime4KCPP::AC::process()+184) (BuildId: 4fe105cdc76f648093e878ef6f2e817ec4055ad3)
> A        #07 pc 00000000000e22ec  /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!libAnime4KCPPCore.so (Java_github_tianzerl_anime4kcpp_wrapper_Anime4K_processAnime4K+32) (BuildId: 4fe105cdc76f648093e878ef6f2e817ec4055ad3)
> A        #10 pc 0000000000000e5c  [anon:dalvik-classes5.dex extracted in memory from /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!classes5.dex] (github.tianzerl.anime4kcpp.wrapper.Anime4K.process+4)
> A        #12 pc 00000000000021fc  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!classes4.dex] (github.tianzerl.anime4kcpp.Anime4KCPPUtil.reSizeBitmap+8)
> A        #14 pc 0000000000004a64  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!classes4.dex] (github.tianzerl.anime4kcpp.TestActivity.lambda$processImage$2$github-tianzerl-anime4kcpp-TestActivity+124)
> A        #16 pc 0000000000004700  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~6-aV_QLj3Vru1wBFHJ2Huw==/github.tianzerl.anime4kcpp-VGJazKt6MGAya45MdhIrbA==/base.apk!classes4.dex] (github.tianzerl.anime4kcpp.TestActivity$$ExternalSyntheticLambda4.run+4)
> 2023-11-28 17:30:52.844 28351-28367 BLASTBufferQueue        github.tianzerl.anime4kcpp           E  [VRI[TestActivity]#0](f:0,a:2) Faking releaseBufferCallback from transactionCompleteCallback
> ---------------------------- PROCESS ENDED (28351) for package github.tianzerl.anime4kcpp ----------------------------
> ```
> 
> 想请教您，该从哪方面入手处理啊
你好，我这边也想把这个应用在android 实时视频上，但是不知道如何下手，可以提供你demo学习下吗？

**Comment by TianZerL** [comment]
@CoderCaiSL
那个安卓版本基本属于放弃了，Anime4KCPP V3已经完全重写了，现在在安卓上测试最简单的办法是Termux直接编译运行。

**Comment by CoderCaiSL** [comment]
> @CoderCaiSL 那个安卓版本基本属于放弃了，Anime4KCPP V3已经完全重写了，现在在安卓上测试最简单的办法是Termux直接编译运行。

@TianZerL 可以出一个详细教程嘛？我这边纯新手，不知道怎么使用Termux直接编译运行

**Comment by TianZerL** [comment]
@CoderCaiSL
在安卓手机上下载安装[termux](https://github.com/termux/termux-app)，然后参考[readme](https://github.com/TianZerL/Anime4KCPP?tab=readme-ov-file#termux)。有其他问题建议新开一个issue。

**Comment by CoderCaiSL** [comment]
> @CoderCaiSL 在安卓手机上下载安装[termux](https://github.com/termux/termux-app)，然后参考[readme](https://github.com/TianZerL/Anime4KCPP?tab=readme-ov-file#termux)。有其他问题建议新开一个issue。

噢噢，懂了，我查了下termux，同时Anime4K的效果其实我已经验证过了，不管是图像优化处理和每一帧图像处理耗时，都是符合我的预期值，但是我需要在android项目中集成使用Anime4K，不想依赖termux那种，但是我不知道咋处理

**Comment by CoderCaiSL** [comment]
> @CoderCaiSL 在安卓手机上下载安装[termux](https://github.com/termux/termux-app)，然后参考[readme](https://github.com/TianZerL/Anime4KCPP?tab=readme-ov-file#termux)。有其他问题建议新开一个issue。
@TianZerL 噢噢，懂了，我查了下termux，同时Anime4K的效果我已经验证过了，不管是图像优化处理和每一帧图像处理耗时，都是符合我的预期值，但是我需要在android项目中集成使用Anime4K，不想依赖termux那种，但是我不知道咋处理

**Comment by TianZerL** [comment]
@CoderCaiSL
Termux上没问题的话，那在Android Studio里面用ndk编译也是没啥问题的，V3版本本身也提供了C语言接口，用jni包装一下就能在java调用。
不过你要注意Anime4K现在和Anime4KCPP关系已经不是很大了，算法不一样，你想用[Anime4K原版](https://github.com/bloc97/Anime4K)的话这个库可能不是你要找的。
Anime4KCPP的C++库在骁龙888上, 480P图像cpu跑用neon加速也就3-4帧，OpenCL用gpu跑能有个10帧多，想要实现实时处理视频可能还有困难。
实时处理可能只能用[GLSL版本](https://github.com/TianZerL/ACNetGLSL)，这个是给mpv播放器写的，配合安卓mpv播放器可以实现手机端实时处理。Anime4K原版也是一系列的GLSL滤镜。
