### ISSUE TITLE
OpenCL dependency for CPU only?

### ISSUE THREAD

**Issue by dgcampea** [TianZerL/Anime4KCPP#16]
Running the CLI version of Anime4KCPP on a machine that doesn't have OpenCL available crashes on launch.

This is present on 1.8.0 and 1.8.1 at least.
To reproduce:
- Launch a Windows Sandbox instance.
- Copy Anime4KCPP files over.
- Execute

**Comment by TianZerL** [comment]
It is OK to run it on a machine which does not supports OpenCL, but make sure you have all the dlls of opencv and opencl even it is not supported.
