### ISSUE TITLE
打不开Anime4KCPP_GUI.exe

### ISSUE THREAD

**Issue by webdq** [TianZerL/Anime4KCPP#17]
![QQ截图20200602141004](https://user-images.githubusercontent.com/17735764/83488404-5f320f80-a4df-11ea-95d1-d54cafb1d900.png)

操作系统：Microsoft Windows 7 旗舰版 (BUILD:7601) (64-bit)
CPU信息：Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
显卡信息：Intel(R) HD Graphics 3000

**Comment by TianZerL** [comment]
显卡太老了，opencl可能不支持，甚至连动态链接库都不带，可以考虑更新驱动或者下载Intel的CPU opencl运行时以获取该dll
________________________________
