### ISSUE TITLE
奇怪的显卡使用策略

### ISSUE THREAD

**Issue by AaronFeng753** [TianZerL/Anime4KCPP#18]
我自行在Windows上编译了`9ac24433b30bedb70133c310a36e044ffb55faaa`版本的Anime4KCPP
发现显卡使用策略十分奇怪, 显存使用的是AMD独显, 而在AMD显卡驱动内看不到GPU占用, 却在任务管理内看到Intel集显使用率很高.
opencv版本:`4.30`
Intel OpenCL SDK: `2020.1.396`
CMake:`3.16.1`
visual studio: `2017社区版`

**Comment by AaronFeng753** [comment]
emmm, 刚提交完issue就发现你发了个release, 等我先看看release会不会有这个问题, 先close了

**Comment by TianZerL** [comment]
AMD显卡占用需要右键，查看compute 0，1，3，4，5等的其中一个，Nvida查看cuda，intel直接看3d

**Comment by AaronFeng753** [comment]
> AMD显卡占用需要右键，查看compute 0，1，3，4，5等的其中一个，Nvida查看cuda，intel直接看3d。
> 如果确定使用的是AMD显卡的话，intel集显应该不是这边在用，唯一可能导致出现双显卡占用的就是开启dxva编码器。

应该是我这显卡驱动的问题, 下载release后发现有时正常显示有时不显示.

**Comment by AaronFeng753** [comment]
顺便问一下, 是否在启用ACNet后预处理后期处理等等一堆自定义设置都会失效??? 
可否说明一下启用ACNet后有哪些自定义设置直接失效了.

**Comment by TianZerL** [comment]
ACNet不支持前后置滤镜和Anime4K09的参数，具体可以下个GUI，选中后被关闭的就是不支持的
