### ISSUE TITLE
 in macOS 10.15.5 , compile success but nothing to do

### ISSUE THREAD

**Issue by awkj** [TianZerL/Anime4KCPP#20]
I do full step , but I run  make .  so output is null , ./bin is null, Can I debug it.

**Comment by TianZerL** [comment]
Any output of CMake?

**Comment by awkj** [comment]
![image](https://user-images.githubusercontent.com/9017743/83897663-72b3d380-a788-11ea-9faa-af09051c6a7b.png)
this is screenshots
I Install all dep dependencies by hombrew

**Comment by TianZerL** [comment]
cd to Anime4KCPP then
```mkdir build && cd build && cmake .. && make```

**Comment by awkj** [comment]
> cd to Anime4KCPP then
> `mkdir build && cd build && cmake .. && make`
> or use cmake gui, which is easier to use

thans thans , I study program fisrt use go / rust / typescript . no  C  no C ++
Get used to using Dockerfile and forget CmakeList.txt to generate makefile

embarrassing

**Comment by TianZerL** [comment]
Hope you like the new ACNet 😂
