### ISSUE TITLE
无法编译CLI

### ISSUE THREAD

**Issue by ccicnce113424** [TianZerL/Anime4KCPP#22]
错误信息：
[download 100% complete]
CMake Error at cmake/ThirdPartyForCLI.cmake:21 (file):
  file DOWNLOAD HASH mismatch

    for file: [C:/Users/ccicnce113424/Desktop/Anime4KCPP-master/ThirdParty/include/cmdline.h]
      expected hash: [da2d7322f5992f832a62a6c95cddfe6565b766ac]
        actual hash: [da39a3ee5e6b4b0d3255bfef95601890afd80709]
             status: [6;"Couldn't resolve host name"]

Call Stack (most recent call first):
  CLI/CMakeLists.txt:13 (include)

Configuring incomplete, errors occurred!
这个文件的hash好像错了

**Comment by TianZerL** [comment]
这是网络的问题，这个文件会从GitHub下载然后检查hash，hash不对说明下载失败。

**Comment by ccicnce113424** [comment]
> 这是网络的问题，这个文件会从GitHub下载然后检查hash，hash不对说明下载失败。

我可以手动下载这个文件吗

**Comment by TianZerL** [comment]
可以，看cmake文件源码，有下载地址

**Comment by JalexHW** [comment]
the link is dead [https://github.com/TianZerL/cmdline/raw/master/cmdline.h](https://github.com/TianZerL/cmdline/raw/master/cmdline.h)
you have changed it a month ago to [https://github.com/TianZerL/cmdline/raw/master/cmdline.hpp](https://github.com/TianZerL/cmdline/raw/master/cmdline.hpp ).. ?
