### ISSUE TITLE
图片中出现横线

### ISSUE THREAD

**Issue by AaronFeng753** [TianZerL/Anime4KCPP#23]
如题, 偶发bug, 图片中会出现这样的横线, 没有任何出现规律, 随机发生, 怀疑与图片绘制有关???
无论是否启用ACNet算法都会出现这种横条.
测试版本: `自行编译的863648bfbf621bf3d9bea1ed4e167de0b7affc71` 以及 `v2.0.0 release`
测试时的软件设置:
```
-z 2 -w -q -H
```
平台: 
```
- Windows 10 专业版 1909
- i7-8550U
- RX 550
```
![2 - 副本 (6)_waifu2x_2x_jpg](https://user-images.githubusercontent.com/52553688/84490657-0c720800-acd6-11ea-91b1-f2e22642e016.png)
![2 - 副本 (8)_waifu2x_2x_jpg](https://user-images.githubusercontent.com/52553688/84490665-0da33500-acd6-11ea-9373-289cbf06be7e.png)
![Snipaste_2020-06-12_17-56-56](https://user-images.githubusercontent.com/52553688/84490710-1eec4180-acd6-11ea-95ea-be2577bc525a.jpg)

**Comment by AaronFeng753** [comment]
原图:
![2 - 副本 (117) - 副本 - 副本](https://user-images.githubusercontent.com/52553688/84491115-a20d9780-acd6-11ea-84ad-340e51f3fe6c.jpg)

**Comment by TianZerL** [comment]
我这边没有复现出来，intel和nvidia显卡都没问题，关掉GPU加速呢？

**Comment by AaronFeng753** [comment]
> 我这边没有复现出来，intel和nvidia显卡都没问题，关掉GPU加速呢？

随机出现的bug当然不能一次就复现出来, 我一次测试了接近四十张图片

**Comment by TianZerL** [comment]
我大概尝试了10多次，每次的md5都是一样的

**Comment by AaronFeng753** [comment]
> 我大概尝试了10多次，每次的md5都是一样的

关闭GPU,关闭ACNet后就没复现出来了
但是开GPU时的确能复现


正常图片的的MD5
```
69B93F686EF43488446749E08616D157
```
出错图片之一的md5
```
A1214F8D7123CFAEDE5D93A7EEF99D6A
```

**Comment by AaronFeng753** [comment]
> 我大概尝试了10多次，每次的md5都是一样的

我怀疑可能与编译时用的是intel的opencl sdk有关?

**Comment by TianZerL** [comment]
关ACNet开GPU加速也出现嘛，感觉是AMD某些显卡驱动的问题，我在intel和nVidia上都无法复现，我再试试A卡。

**Comment by AaronFeng753** [comment]
关ACNet开GPU加速 也复现出来了:
![2 - 副本](https://user-images.githubusercontent.com/52553688/84494839-c2405500-acdc-11ea-96e0-69769cf93a87.png)
等一下我试试更新显卡驱动...

**Comment by TianZerL** [comment]
在Vega8 20.4.2版驱动上也没复现出，测试了50次

**Comment by AaronFeng753** [comment]
我这最新版驱动更完犊子，直接蓝屏了

**Comment by AaronFeng753** [comment]
正跑着呢，蓝屏重启了

**Comment by TianZerL** [comment]
不会吧，你用DDU清理一次再安装呢

**Comment by AaronFeng753** [comment]
> 不会吧，rx550好歹也是北极星架构，驱动支持还是有的，你用DDU清理一次再安装呢

不是驱动装完直接蓝屏了，是跑着anime4kcpp，跑半道蓝屏了

**Comment by TianZerL** [comment]
那你可以试试19驱动的最后一版19.12.2，对北极星可能稳一点，20驱动基本在修5700xt的bug。

**Comment by AaronFeng753** [comment]
成功跑完了, 更新驱动后虽然蓝屏一次, 但是没再出现横线了🥳🥳🥳
