### ISSUE TITLE
请问如何在MPV中使用呢

### ISSUE THREAD

**Issue by OolongFox** [TianZerL/Anime4KCPP#24]
配置好了VapourSynth，但是不知道怎么写.vpy才能让本项目在mpv中使用

**Comment by TianZerL** [comment]
MPV中为什么不直接使用glsl呢，也就是原版anime4k，如果需要在mpv中使用vapoursynth插件的话，参考archlinux的[wiki](https://wiki.archlinux.org/index.php/Mpv_(简体中文)#Vapoursynth)

**Comment by OolongFox** [comment]
> MPV中为什么不直接使用glsl呢，也就是原版anime4k，如果需要在mpv中使用vapoursynth插件的话，参考archlinux的[wiki](https://wiki.archlinux.org/index.php/Mpv_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#Vapoursynth)

感谢回复，原版A4K3.1有在用，主要是想看看ACNet在mpv里实际播放视频如何。

**Comment by TianZerL** [comment]
更简单的应该是用potplayer，不需要自己编译就能用vapoursynth脚本，但效率偏低
