### ISSUE TITLE
Not understood the output path in the apk

### ISSUE THREAD

**Issue by Noamcelermajer** [TianZerL/Anime4KCPP#25]
I tried upscaling some drawing but an error pop saying that the app couldnt create folder
i tried changing path and everything but
i dont understand the way it work is it relative to something or is it from /storage

**Comment by TianZerL** [comment]
Make sure that you have authorized the apk to read/write the sd card

**Comment by Noamcelermajer** [comment]
Ok 
I checked the permission everything set
i created a Anime4KCPP/output
on storage/emulated/0
there is right now no error it say just finished %time
but no file is actually saved

**Comment by TianZerL** [comment]
I think it is actually didn't be authorized  to write file to the sd card. What the prefix of path string of input file in the process list, `storage/emulated/0/`?

**Comment by Noamcelermajer** [comment]
yeah 
input path is 
/storage/emulated/0/myDraw.png

**Comment by Noamcelermajer** [comment]
i did reinstall the app even tried older version

**Comment by TianZerL** [comment]
what is the android version of you phone？

**Comment by Noamcelermajer** [comment]
android 10 op7p beta 15

**Comment by TianZerL** [comment]
Try to set ouput path as `Android/data/github.tianzerl/anime4kcpp/output`, it looks like android 10 didn't allow app to create file in the root of sd card.

**Comment by Noamcelermajer** [comment]
oK the error just pop 
Unavle to create files 
also there is no 
android/data/github.tianzerl.anime4kcpp
file 
is that normal?

**Comment by TianZerL** [comment]
normally there is no `Android/data/github.tianzerl.anime4kcpp/files/output` by default, if you set `Output path` as it, it will be create automatically.

**Comment by Noamcelermajer** [comment]
Well if this works on you it probably a problem onmy end which i will try to fix later maybe some kind a problem with permission on beta ( android 10 op7p beta 15) 
Anyways thank u for ur work And help :)

**Comment by zheyangshi** [comment]
按照这里的指示，创建了相应的文件夹~运行成功无报错，但是没有产生输出文件（安卓系统9.1）

**Comment by TianZerL** [comment]
@zheyangshi 
默认会自动创建输出文件夹，位置在Android/data/github.tianzerl.anime4kcpp/files/output，安卓9应该可以设置到其它更方便的位置，没有权限问题

**Comment by zheyangshi** [comment]
好的谢谢大佬，不过那就奇怪了，我一开始用默认的路径，提示我无法创造文件夹，所以我参照这个issue中你的回答，自己创了相应文件夹，然后就出现刚才的问题，成功但是无结果报错，我再试试！

**Comment by TianZerL** [comment]
@zheyangshi
有的定制系统的权限管理更严格，要确保给了读写权限，你这个多半是没权限。

**Comment by zheyangshi** [comment]
soga，我再去试试哈~谢谢！

**Comment by zheyangshi** [comment]
昨天问题已经成功了，非常感谢，就是权限安装的时候需要打开！再想请问一个，我注意到ACNet的参数那部分，是全手敲进去的，这个网络参数获得过程是什么样的呀~是在别的框架下训练出来，然后取出来吗

**Comment by TianZerL** [comment]
@zheyangshi 
是的，用其他框架训练的

**Comment by zheyangshi** [comment]
好的，谢谢同学~
