### ISSUE TITLE
Android app errors

### ISSUE THREAD

**Issue by Mimocro** [TianZerL/Anime4KCPP#28]
Failed to create folders (always) and failed to initialize video writer (shows only when i try to start it on 
 any videos).
I'm trying to change preference and output folder, but it does nothing. It finishes running on pictures, but first error shows after finished message. Also if quit for app with quit button, at next start gpu modes can't be chosen and shows as unsupported. And more thing, after change screen orientation all settings and selecting files resets.

**Comment by TianZerL** [comment]
Failed to create folders may happen on some Android 10 devices，I will try to fix it in next version.  
Failed to initialize video writer is like failed to create folders, it should be a permission problem.
GPU mode bug has been fixed.

**Comment by Mimocro** [comment]
Ok, it fix errors, but i have Android 9.

**Comment by TianZerL** [comment]
I have tested in my Lenovo ZUI11.5(Android 10) and ZUI4(Android 8) device, all works well, I'm not sure if it is more strict of permission management in native android.
