### ISSUE TITLE
可否为ACNet算法加入指定显卡的功能?

### ISSUE THREAD

**Issue by AaronFeng753** [TianZerL/Anime4KCPP#29]
如题, 希望能为ACNet算法加入指定 `平台ID,设备ID` 的功能, 也就是可以指定显卡

**Comment by AaronFeng753** [comment]
才发现本来是支持的, 抱歉.
之前看gui不支持我就以为cui也不支持来着

**Comment by TianZerL** [comment]
GUI也支持啊，就安卓不支持，因为没必要，其他都支持

**Comment by AaronFeng753** [comment]
> GUI也支持啊，就安卓不支持，因为没必要，其他都支持

我就用过一次老版的(ACNet刚加入时候的), 新版的GUI我还没用, 所以弄错了, 抱歉, 打扰了.
