### ISSUE TITLE
CMD调用时，如果启用GPU加速，则无法在调用时带上路径

### ISSUE THREAD

**Issue by AaronFeng753** [TianZerL/Anime4KCPP#3]
如题，若启用GPU加速，则在使用CMD命令行调用CLI时带上完整路径后会提示:
```
Read kernel error
```
带上完整路径的意思是这样调用软件：
```
"D:/xxxx/新建文件夹/Anime4K/Anime4K.exe" -i "D:/xxxx/xxxx/10.png" -o "D:/xxxxx/xxxx/xxxx/10.png" -z 2 -p 1 -n 1 -c 0.30 -g 1.00 -q
```
即在调用软件时，带上了软件所在的完整路径`D:/xxxx/新建文件夹/Anime4K/Anime4K.exe`后再启用GPU加速，就会提示`Read kernel error`. 

如果把完整路径去掉，在软件所在位置为初始路径调用命令行，其他参数不变，就不会出现错误，即像下面这样：
```
Anime4K.exe -i "D:/xxxx/xxxx/10.png" -o "D:/xxxxx/xxxx/xxxx/10.png" -z 2 -p 1 -n 1 -c 0.30 -g 1.00 -q
```
如果其他参数不变，关闭GPU加速，依旧使用完整路径调用软件，则可以正常运行处理图片。
```
"D:/xxxx/新建文件夹/Anime4K/Anime4K.exe" -i "D:/xxxx/xxxx/10.png" -o "D:/xxxxx/xxxx/xxxx/10.png" -z 2 -p 1 -n 1 -c 0.30 -g 1.00
```

**Comment by TianZerL** [comment]
这个问题在于现阶段我为了保证可调式性，kernel并未直接集成于源码中，而是以cl文件的形式随二进制程序发布，且在read kernel的时候采用了相对路径，因此需要保证cl文件路径和你命令行的当前工作目录相同。考虑将Anime4KCPPKernel.cl文件复制到命令行工作目录。

**Comment by AaronFeng753** [comment]
谢谢老铁解答！👍👍👍问题立马解决了！！！👍👍👍👍
