### ISSUE TITLE
FFAudioSource：Cant open X://.....不支持SMB的网络驱动器吗

### ISSUE THREAD

**Issue by kmyqchy** [TianZerL/Anime4KCPP#31]

**Comment by TianZerL** [comment]
FFAudioSource打不开是因为ffms2插件无法解码这个音频吧，而不是SMB的问题，你可以换一个音频解码器。

**Comment by ccicnce113424** [comment]
@TianZerL FFmpegSource太久没更新了。[这里](https://github.com/HolyWu/L-SMASH-Works/releases/) 是L-SMASH源滤镜的一个活跃的分支，同样基于libavcodec。
