### ISSUE TITLE
可否在图片处理完成后再写入硬盘

### ISSUE THREAD

**Issue by AaronFeng753** [TianZerL/Anime4KCPP#32]
当前软件的策略貌似是边生成图像边写入硬盘, 导致如果进程被强制关闭, 会在硬盘内留下一个看似正常(名字, 分辨率什么参数都有), 但是实际上一大半都是黑色的坏掉的图片

所以可否更改为将生成的图像先缓冲在内存中, 整个图片处理完毕后再一起写入硬盘？？？

**Comment by TianZerL** [comment]
就是处理完图像再写入硬盘的，强制关闭会导致析构函数被提前调用，从而写入缓存到硬盘。

**Comment by AaronFeng753** [comment]
好的, 谢谢解答!!👍
