### ISSUE TITLE
视频处理后输出的码率能否手动调整

### ISSUE THREAD

**Issue by aliofwind** [TianZerL/Anime4KCPP#33]
刚刚试了试放大一个5分钟的lol游戏录像，源视频是1080P 60FPS AVC编码5Mbps，用ACNet算法+GPU加速+dxva选项放大到2160P，输出的文件体积高达15GB，码率400Mbps左右，这个体积有点恐怖，能不能手动调整视频处理输出后的码率，或者通过管道输出给ffmpeg、NVEncC等CLI软件进行压制

**Comment by TianZerL** [comment]
请使用AviSynthPlus或者VapourSynth进行压制，GUI和CLI只是一种快速使用方式，这些复杂的功能应当交由AviSynthPlus或者VapourSynth。
