### ISSUE TITLE
CLI能否实现用管道(pipe)输入输出

### ISSUE THREAD

**Issue by ccicnce113424** [TianZerL/Anime4KCPP#34]
虽然指定文件名为cin(限定Windows)可以暂时解决问题，但我希望CLI能够真正支持管道输入输出。这样就可以使用各种编解码器，可以指定更多参数。

**Comment by TianZerL** [comment]
需要压制和管道输入输出为什么不用vapoursynth和avisynth呢，CLI和GUI只是快速方便使用，压制功能应该交给vapoursynth和avisynth。
