### ISSUE TITLE
Losing Transparency

### ISSUE THREAD

**Issue by WalkerMx** [TianZerL/Anime4KCPP#37]
I'm using Anime4KCPP CLI 2.2.1

When Converting/Up-scaling/Filtering, transparency is not preserved. 

Am I doing something wrong, or is this "working as intended"?

**Comment by TianZerL** [comment]
Yes,  it is working as intended, alpha channel is not supported now.

**Comment by WalkerMx** [comment]
Understood.

Thank you for your time!
