### ISSUE TITLE
[GUI] Fix typo `Warning FFmpeg not fount`

### ISSUE THREAD

**Issue by dvdvideo1234** [TianZerL/Anime4KCPP#38]
Hello,

1. It appears to be `FFmpeg not found !`
2. How can I point the application to the `FFmpeg` of [`MPC-HC`](https://codecguide.com/download_kl.htm)

Where do I need to `Install` the executable `ffmpeg.exe`.
1. Extracting the `ffmpeg` project in the application holder appears to have no effect.
2. The path to the `ffmpeg` executable will be best stored in `settings.ini`

**Comment by TianZerL** [comment]
Thanks, I will fix the typo.
> Where do I need to Install the executable ffmpeg.exe.

You can extract the ffmpeg binary to the root directory of GUI (same as the `Anime4KCPP_GUI.exe`) or add ffmpeg bin folder to your system environment variable.

> The path to the ffmpeg executable will be best stored in settings.ini

That's a good idea.

**Comment by dvdvideo1234** [comment]
> You can extract the `ffmpeg` binary to the root directory of GUI (same as the Anime4KCPP_GUI.exe) 

Sadly I tried [this](https://ffmpeg.zeranoe.com/builds/) first, and stored the `bin`, `doc` and `presets` where the `*.exe` is located, but it does not seem to detect it either.

 That's why I think the best option is to store it in `settings.ini` for example `rootFFmpeg`:
```
[GUI]
language=en
quitConfirmatiom=true
checkFFmpeg=true
rootFFmpeg="D:\Anime4KCPP_GUI\FFmpeg"
```
Note that the folder looks line this:
![image](https://user-images.githubusercontent.com/9112662/90772160-efbd0680-e2fc-11ea-9ff5-206d580fe69c.png)

**Comment by TianZerL** [comment]
You need copy all the files in the `bin` to the same folder as `Anime4KCPP_GUI.exe`, I mean, to make `Anime4KCPP_GUI.exe` and `ffmpeg.exe` in the same folder.
