### ISSUE TITLE
[Features request]有没有可能支持在avisynth脚本中调用呢？

### ISSUE THREAD

**Issue by YohoYang** [TianZerL/Anime4KCPP#4]
通过avisynth的avs脚本挂载有诸多好处
1.可以自定义预处理后处理滤镜以及anime4k的处理位置
2.可以同时添加字幕
3.将图像一次处理减少多次压缩对画面造成的损失

观察后发现avisynth的实现与Anime4KCPP很类似
1.avisynth的filters是cpp
2.avisynth通常使用ffmpeg挂载视频

如果可以支持那就最好啦，感谢

**Comment by TianZerL** [comment]
我并不是很熟悉avisynth，但我会研究该方案的可行性，但最后可能会以单独的avisynth filter的方式提供。

Anime4KCPP是以标准C++写成，支持任何可以绑定到C++类的语言调用，并不具有平台或者编译器依赖性，但它目前只支持视频文件的直接输入并在处理完后直接编码为avc1格式的mp4文件，并不支持输入输出视频流，因此avisynth可能无法直接调用。 
 
目前ffmpeg仅用于合并音轨，并未用于视频处理，视频处理使用OpenCV的接口直接实现。若您希望将其用于视频压制，可以考虑在最后压制前使用Anime4KCPP进行一次处理，此后进行参数合理的二次压制并不会降低画质。Anime4KCPP通过GPU加速，会尽量将视频处理时间控制在合理范围内（目标是1080P至4K处理短于视频时长）

**Comment by YohoYang** [comment]
> 我并不是很熟悉avisynth，但我会研究该方案的可行性，但最后可能会以单独的avisynth filter的方式提供。
> 
> Anime4KCPP是以标准C++写成，支持任何可以绑定到C++类的语言调用，并不具有平台或者编译器依赖性，但它目前只支持视频文件的直接输入并在处理完后直接编码为avc1格式的mp4文件，并不支持输入输出视频流，因此avisynth可能无法直接调用。
> 
> 目前ffmpeg仅用于合并音轨，并未用于视频处理，视频处理使用OpenCV的接口直接实现。若您希望将其用于视频压制，可以考虑在最后压制前使用Anime4KCPP进行一次处理，此后进行参数合理的二次压制并不会降低画质。Anime4KCPP通过GPU加速，会尽量将视频处理时间控制在合理范围内（目标是1080P至4K处理短于视频时长）

感谢！会尝试建议的步骤。也期待filter的版本！

**Comment by TianZerL** [comment]
现在已经支持VapourSynth啦😀

**Comment by YohoYang** [comment]
> 现在已经支持VapourSynth啦😀

感谢！这么快就搞定了！
不过VapourSynth的话就需要另外安装插件来处理了，不过也可以~
再次感谢~

**Comment by TianZerL** [comment]
之所以选择VapourSynth，一是跨平台考虑，AviSynth只支持Windows，甚至64位都没法很好的支持；二是AviSynth对于编译器实在是太挑剔了，官方甚至推荐使用老掉牙的VC6。而Anime4KCPP基于C++17标准开发，致力于全平台，不限制编译器。

**Comment by YohoYang** [comment]
> 之所以选择VapourSynth，一是跨平台考虑，AviSynth只支持Windows，甚至64位都没法很好的支持；二是AviSynth对于编译器实在是太挑剔了，官方甚至推荐使用老掉牙的VC6。而Anime4KCPP基于C++17标准开发，致力于全平台，不限制编译器。

嗯，avisynth确实太老了，慢慢的也差不多会淘汰了

**Comment by ccicnce113424** [comment]
> 之所以选择VapourSynth，一是跨平台考虑，AviSynth只支持Windows，甚至64位都没法很好的支持；二是AviSynth对于编译器实在是太挑剔了，官方甚至推荐使用老掉牙的VC6。而Anime4KCPP基于C++17标准开发，致力于全平台，不限制编译器。

请考虑AviSynth+版本
目前有大量的视频播放器，视频解码器，甚至非线性视频编辑器可以通过某种方法使用AviSynth+插件。AviSynth+也对多线程进行了优化。[AVFS](https://turtlewar.org/avfs/)，[avs4x26x](https://github.com/astrataro/avs4x26x)等软件可以导出处理后的文件。[小丸工具箱](https://maruko.appinn.me/)，[MeGui](https://sourceforge.net/projects/megui/)，[格式工厂](http://www.pcgeshi.com/index.html)等热门工具同样自带AviSynth+。而VapourSynth脚本的编写需要Python基础，可能会对压制工作者带来额外负担。VapourSynth对于部分AviSynth插件有兼容性问题。VapourSynth现在也不是非常成熟。

**Comment by TianZerL** [comment]
@ccicnce113424 
Anime4K算法设计之初就是针对RGB24的，在i5 4590+RX570的机器上，480P拉960P，开启YUV420转RGB24，Anime4KCPP处理，再转YUV444后fps依然在90以上，4K也有23帧，我认为性能已经不构成瓶颈。

**Comment by ccicnce113424** [comment]
> @ccicnce113424
> Anime4K算法设计之初就是针对RGB24的，在i5 4590+RX570的机器上，480P拉960P，开启YUV420转RGB24，Anime4KCPP处理，再转YUV444后fps依然在90以上，4K也有23帧，我认为性能已经不构成瓶颈。

有计划适配吗？

**Comment by TianZerL** [comment]
@ccicnce113424
关于AviSynth+的适配我会研究的，关于AviSynth+的开发文档比较少，但如果AviSynth+插件的开发和AviSynth是一样的sdk的话我可能没法适配，因为AviSynth支持的最新编译器也没法编译C++17

**Comment by ccicnce113424** [comment]
> @ccicnce113424
> 关于AviSynth+的适配我会研究的，关于AviSynth+的开发文档比较少，但如果AviSynth+插件的开发和AviSynth是一样的sdk的话我可能没法适配，因为AviSynth支持的最新编译器也没法编译C++17

(Doom9论坛上相关的内容)[https://forum.doom9.org/showpost.php?p=1712979&postcount=938]，可能对你有用

**Comment by ccicnce113424** [comment]
> 之所以选择VapourSynth，一是跨平台考虑，AviSynth只支持Windows，甚至64位都没法很好的支持；二是AviSynth对于编译器实在是太挑剔了，官方甚至推荐使用老掉牙的VC6。而Anime4KCPP基于C++17标准开发，致力于全平台，不限制编译器。

AviSynth+官方推荐用Visual Studio 2013 Community Version编译，不知道是否支持最新版本的Visual Studio。
http://forum.doom9.org/showthread.php?t=168856

**Comment by ccicnce113424** [comment]
> @ccicnce113424
> 关于AviSynth+的适配我会研究的，关于AviSynth+的开发文档比较少，但如果AviSynth+插件的开发和AviSynth是一样的sdk的话我可能没法适配，因为AviSynth支持的最新编译器也没法编译C++17

你可以尝试安装AviSynth+最新版本
![image](https://user-images.githubusercontent.com/30774232/82751355-290ed480-9de9-11ea-995a-77bee3ee0358.png)
安装后你应该就可以在AviSynth+的安装目录找到开发文档（英文）和滤镜开发SDK了

**Comment by TianZerL** [comment]
@ccicnce113424  
现已支持AviSynthPlus插件，请下载Beta版帮助测试。

**Comment by ccicnce113424** [comment]
> @ccicnce113424
> 现已支持AviSynthPlus插件，请下载Beta版帮助测试。

小丸还有MeGui只包含32位AVS+，想自己编译一个32位版本在主流工具上调试，Windows上用MinGW怎么配置开发环境

**Comment by TianZerL** [comment]
@ccicnce113424<https://github.com/ccicnce113424>
clone项目，修改cmake文件夹下vs和asp的库为32位，根据提示设置路径，生成然后编译，注意mingw64无法编译cli(不完整支持c++=17)

________________________________

**Comment by ccicnce113424** [comment]
> @ccicnce113424 至少提前准备好opencv(官方只提供vs的64位预编译版本，你需要自己编译32位mingw的库)，opencl sdk(建议Intel的)，avisynth+的sdk。 clone项目，修改cmake文件夹下vs和asp的库为32位，根据提示设置路径，生成然后编译，注意mingw64无法编译cli(不完整支持c++=17)

编译AVS的插件要用VS的库？

**Comment by TianZerL** [comment]
不用，但你要注意AVS是基于C++的而且是MSVC编译的，mingw可能链接失败的

**Comment by ccicnce113424** [comment]
> @ccicnce113424
> 不用，但你要注意AVS是基于C++的而且是MSVC编译的，mingw可能链接失败的

确实，链接失败，开发环境是MSYS2，OpenCL，OpenGL都正确配置
一堆错误信息的末尾都类似这样：undefined reference to `operator delete(void*, unsigned int)'
难道我MSYS2没配置好？

**Comment by TianZerL** [comment]
MSVC和Mingw二进制不兼容, 你可能要先重新编译AVS

**Comment by ccicnce113424** [comment]
错误信息部分截图：
![image](https://user-images.githubusercontent.com/30774232/83318533-6f8c8500-a268-11ea-8ebe-eea77bf822e2.png)
应该是没配置好

**Comment by TianZerL** [comment]
@ccicnce113424  
所有C++写的库都必须用mingw重新编译

**Comment by ccicnce113424** [comment]
> @ccicnce113424
> 所有C++写的库都必须用mingw重新编译

我放弃了
小丸还有MeGui只包含32位AVS+，下次出release的时候请编译一个32位版本的AVS+插件，便于使用。VS，CLI，GUI版本都没必要出32位的。

**Comment by TianZerL** [comment]
@ccicnce113424
下一个release版本的重心是引入全新的卷积神经网络算法ACNet，大幅改善质量，由于编译32位需要重新编译的第三方库较多，在下一个release可能依然不会提供官方32位版本，待ACNet算法测试稳定后，会提供32位版本的。

**Comment by ccicnce113424** [comment]
> @ccicnce113424
> 下一个release版本的重心是引入全新的卷积神经网络算法ACNet，大幅改善质量，由于编译32位需要重新编译的第三方库较多，在下一个release可能依然不会提供官方32位版本，待ACNet算法测试稳定后，会提供32位版本的。

最新版本使用VC2019编译通过（32位，自己编译OpenCV）
[AviSynthPlus_Plugin_Win32_build.zip](https://github.com/TianZerL/Anime4KCPP/files/4739762/AviSynthPlus_Plugin_Win32_build.zip)

**Comment by ccicnce113424** [comment]
未经测试，不知道是否能使用ACNet

**Comment by ccicnce113424** [comment]
> @ccicnce113424
> 下一个release版本的重心是引入全新的卷积神经网络算法ACNet，大幅改善质量，由于编译32位需要重新编译的第三方库较多，在下一个release可能依然不会提供官方32位版本，待ACNet算法测试稳定后，会提供32位版本的。

msys2管理第三方库很方便（pacman），而且gcc版本也比较高（9.2.0）

**Comment by TianZerL** [comment]
@ccicnce113424
ACNet不依赖任何第三方库，完全手撸C++和OpenCL实现，理论上只要编译过就可用。

**Comment by ccicnce113424** [comment]
> @ccicnce113424
> ACNet不依赖任何第三方库（当然还需要OpenCV来完成基本的图像IO和容器），完全手撸C++和OpenCL实现，理论上只要编译过就可用。
> 我测试后发现GPU加速在某些显卡上有问题（NVIDA GTX1050不正常，Intel核显正常），其余正常。
> 建议你编译的时候使用Intel的OpenCL SDK。猜测可能是某些OpenCL的sdk对32位支持有问题。

用的就是Intel的OpenCL SDK。本人使用Intel核显，GPU加速正常

**Comment by TianZerL** [comment]
那应该是nVidia的锅了，我这里intel核显也正常

**Comment by ccicnce113424** [comment]
> @ccicnce113424
> 那应该是nVidia的锅了，我这里intel核显也正常
@TianZerL 
据我所知，NVIDIA的OpenCL SDK包含在CUDA Toolkit里面

**Comment by TianZerL** [comment]
@ccicnce113424
NVIDIA的SDK版本很老，并不适合用来编译。SDK用谁家的其实大家都能用，主要看版本和稳定性。

**Comment by YohoYang** [comment]
啊，我也希望AviSynthPlus的release能有32bit版本，在用64bit测试版megui测试的时候，挂载后预览直接闪退了……不知道是测试版megui的问题还是什么别的问题，如果不预览直接压制的话，就提示error了。

AVS如下
`Loadplugin("C:\Users\yohoy\Downloads\MeGUI-2913-64\tools\ffms\ffms2.dll") 
LoadPlugin("C:\Users\yohoy\Downloads\Anime4KCPP_AviSynthPlus_plugin-2.2.1-Win64-msvc\AviSynthPlus\dll\Anime4KCPP_AviSynthPlus.dll")

FFVideoSource("D:\CONAN\WORK\bb.mkv", fpsnum = 24000, fpsden = 1001).Anime4KCPP(GPUMode=false,zoomFactor=2,ACNet=true,HDN=false)`

使用的megui是这个（32位也是最新版，但是最新版没有办法测试。楼上上传的一个32位旧版压制也error
[https://sourceforge.net/projects/megui/files/megui-test/2913/](megui-64bit测试版)

压制报错内容如下：
`-[Error] Log for job1 (video, p1.avs -> p1.264)
--[Information] [2020/7/1 20:06:02] Started handling job
--[Information] [2020/7/1 20:06:02] Preprocessing
--[Information] [2020/7/1 20:06:02] AviSynth input script
---[NoImage] Loadplugin("C:\Users\yohoy\Downloads\MeGUI-2913-64\tools\ffms\ffms2.dll") 
---[NoImage] LoadPlugin("C:\Users\yohoy\Downloads\Anime4KCPP_AviSynthPlus_plugin-2.2.1-Win64-msvc\AviSynthPlus\dll\Anime4KCPP_AviSynthPlus.dll")
---[NoImage] FFVideoSource("D:\CONAN\WORK\bb.mkv", fpsnum = 24000, fpsden = 1001).Anime4KCPP(GPUMode=true,zoomFactor=2,ACNet=true,HDN=false)
--[Information] [2020/7/1 20:06:03] resolution: 3840x2160
--[Information] [2020/7/1 20:06:03] frame rate: 24000/1001
--[Information] [2020/7/1 20:06:03] frames: 35485
--[Information] [2020/7/1 20:06:03] length: 00:24:40.020
--[Information] [2020/7/1 20:06:03] aspect ratio: 16:9 (1.778)
--[Information] [2020/7/1 20:06:03] color space: I420
--[Information] [2020/7/1 20:06:03] changing --ref to 1
--[Warning] [2020/7/1 20:06:03] --vbv-bufsize is not restricted. Maximum value for level 4.1 is 78125. Playback may be affected. Reselect AVC level/profile or target playback device in the x264 preset to set the proper value.
--[Warning] [2020/7/1 20:06:03] --vbv-maxrate is not restricted. Maximum value for level 4.1 is 62500. Playback may be affected. Reselect AVC level/profile or target playback device in the x264 preset to set the proper value.
--[Information] [2020/7/1 20:06:03] Job command line: "C:\Users\yohoy\Downloads\MeGUI-2913-64\tools\x264\x264.exe" --level 4.1 --preset veryslow --crf 22.0 --deblock 1:1 --keyint 345 --min-keyint 0 --scenecut 50 --qcomp 0.5 --aq-strength 0.6 --psy-rd 0.4:0 --sar 1:1 --frames 35485 --output "D:\CONAN\WORK\p1.264" "D:\CONAN\WORK\p1.avs" 
--[Information] [2020/7/1 20:06:04] Process started
--[Information] [2020/7/1 20:06:04] Standard output stream
--[Information] [2020/7/1 20:06:04] Standard error stream
--[Error] [2020/7/1 20:06:08] Process exits with error: 0xC0000005 STATUS_ACCESS_VIOLATION (-1073741819)
--[Information] [2020/7/1 20:06:08] Job completed`

不知道是哪里使用上的问题还是其它可能。release中的GUI测试时是可以正常工作的，但avisynth插件不行。

**Comment by TianZerL** [comment]
@YohoYang   
我认为这是MeGUI内置AviSynth+版本太老的缘故，MeGUI是基于C#的，从文件来看也有一个叫做`AvisynthWrapper.dll`的库，看名字想必是用于把AviSynth+的核心库绑定到C#的。  


Anime4KCPP插件基于最新版AviSynth+库编译，而新版AviSynth+库从单从体积来看是内置版本的2倍多，猜想改动比较多，部分c#绑定可能已经失效导致运行时各种错误，而且我发现MeGUI一旦禁用内置AviSynth+而用系统中装好的最新版，或者用新版的Dll覆盖内置的版本，就表现的极为不正常，连软件都打不开。

  
所以我猜测MeGUI现阶段的Wrapper库太老，无法兼容新版AviSynth+，解决方法不是基于32位重新编译，而是应该用一个老版本的AviSynth+的库去编译Anime4KCPP，才能在MeGUI上正常运行，或者MeGUI更新Wrapper以兼容新版AviSynth+，但MeGUI实在太过保守了。建议采用[AvsPmod](https://github.com/gispos/AvsPmod/releases/tag/2.6.2.7)写好脚本后投喂ffmpeg或者x264等进行压制。

**Comment by YohoYang** [comment]
> @YohoYang
> 我认为这是MeGUI内置AviSynth+版本太老的缘故，MeGUI是基于C#的，从文件来看也有一个叫做`AvisynthWrapper.dll`的库，看名字想必是用于把AviSynth+的核心库绑定到C#的。
> 
> Anime4KCPP插件基于最新版AviSynth+库编译，而新版AviSynth+库从单从体积来看是内置版本的2倍多，猜想改动比较多，部分c#绑定可能已经失效导致运行时各种错误，而且我发现MeGUI一旦禁用内置AviSynth+而用系统中装好的最新版，或者用新版的Dll覆盖内置的版本，就表现的极为不正常，连软件都打不开。
> 
> 所以我猜测MeGUI现阶段的Wrapper库太老，无法兼容新版AviSynth+，解决方法不是基于32位重新编译，而是应该用一个老版本的AviSynth+的库去编译Anime4KCPP，才能在MeGUI上正常运行，或者MeGUI更新Wrapper以兼容新版AviSynth+，但MeGUI实在太过保守了。建议采用[AvsPmod](https://github.com/gispos/AvsPmod/releases/tag/2.6.2.7)写好脚本后投喂ffmpeg或者x264等进行压制。

原来是这样，那我试试avspmod吧，感谢~

**Comment by TianZerL** [comment]
> @TianZerL Same error often got 0xC0000005 STATUS_ACCESS_VIOLATION (-1073741819) using VapourSynth R66 with StaxRip

What is the filter version? 2.5 or v3?

**Comment by YKefasu** [comment]
> > @TianZerL Same error often got 0xC0000005 STATUS_ACCESS_VIOLATION (-1073741819) using VapourSynth R66 with StaxRip
> 
> What is the filter version? 2.5 or v3?

Using StaxRip-v2.41.6-x64, with [Release version v2.5.0](https://github.com/TianZerL/Anime4KCPP/releases/tag/v2.5.0)

tcFile = r"%temp_file%_timestamps.txt" # timestamps file path
clip = core.ffms2.Source(r"%source_file%", cachefile=r"%source_temp_file%.ffindex", timecodes=tcFile, threads=0) if os.path.exists(tcFile) else core.ffms2.Source(r"%source_file%", cachefile=r"%source_temp_file%.ffindex")

core.std.LoadPlugin(r"E:\Non-Installer Program\StaxRip-v2.41.6-x64\Settings\Plugins\VapourSynth\Anime4KCPP\dll\Anime4KCPP_VapourSynth.dll", altsearchpath=True)
clip = core.anime4kcpp.Anime4KCPP(clip, ACNet = 1, safeMode = 1, GPUMode = 1, deviceID = 0, platformID = 0, GPGPUModel="CUDA", strengthColor = 0.5, pushColorCount = 1, strengthGradient = 0.5)
