### ISSUE TITLE
无法定位到程序入口（输入点）

### ISSUE THREAD

**Issue by wwsq1149** [TianZerL/Anime4KCPP#40]
我在搞Waifu2x的时候原本想用Anime4K的（我的电脑之前支持GPU的），结果现在兼容性测试Anime4K的CPU和GPU都过不了，图
![image](https://user-images.githubusercontent.com/70135780/91064602-08614f80-e662-11ea-92d1-bfb120a8806d.png)
然后我点开程序的Anime4K目录运行Anime4K_waifu2xEX.exe发现错误
![image](https://user-images.githubusercontent.com/70135780/91064789-4d858180-e662-11ea-8299-151e00870127.png)
然后我就到Anime4KCPP的Github页面下载了Anime4KCPP的GUI版本，也是同样的错误
![image](https://user-images.githubusercontent.com/70135780/91064960-7c9bf300-e662-11ea-9fd0-654585ac6b29.png)
我的显卡很老，Intel Graphics HD 4000核显，所以要效率比较高的方式
系统是Win10 2004专业工作站版本
![image](https://user-images.githubusercontent.com/70135780/91065275-d997a900-e662-11ea-957f-1d8045cd8b7d.png)
显卡驱动是最新的

**Comment by TianZerL** [comment]
这个显卡不支持opencl 1.2吧。

**Comment by wwsq1149** [comment]
运行时当时没找到。。。好不容易才找到。。
CPU可以了，但是GPU死活不能用，显卡驱动一直装，列出GPU也可以看到
![image](https://user-images.githubusercontent.com/70135780/91125019-434f9b80-e6d3-11ea-84ac-ebd463541b29.png)
但是用GPU就崩溃
下面是CPU：
![image](https://user-images.githubusercontent.com/70135780/91125105-83af1980-e6d3-11ea-832f-40e84d273af8.png)
GPU设置：
![image](https://user-images.githubusercontent.com/70135780/91125142-99244380-e6d3-11ea-893b-711bfce2ea59.png)
GPU运行：
![image](https://user-images.githubusercontent.com/70135780/91125181-b0fbc780-e6d3-11ea-872a-4ab9e24219d2.png)
然后就崩溃了。。
在Waifu2x里也是CPU可用，GPU不可用
![image](https://user-images.githubusercontent.com/70135780/91125372-2ebfd300-e6d4-11ea-9ed5-42faa9aebc26.png)

我在Intel的官网上找发现OpenCL Runtime结果跟我提示包含在驱动里。。。
![image](https://user-images.githubusercontent.com/70135780/91125648-c58c8f80-e6d4-11ea-8e00-a23996a02dca.png)

**Comment by TianZerL** [comment]
hd4000原生支持opencl 1.1，对于opencl 1.2我不确定是否后期兼容支持完全了，程序中是用到了1.2的特性的。当然崩溃的原因也可能是图片过大(CPU跑了4s+)，显存不够(这种情况应该是会有报错提示的)。

**Comment by TianZerL** [comment]
这有个用Nvidia的OpenCL 1.2 编译的版本，你可以试试能不能用.


[Anime4KCPP_2.4.0_Beta_with_opencl_1.2_nvidia.zip](https://github.com/TianZerL/Anime4KCPP/files/5121780/Anime4KCPP_2.4.0_Beta_with_opencl_1.2_nvidia.zip)

**Comment by wwsq1149** [comment]
行啊
还是我太菜
![image](https://user-images.githubusercontent.com/70135780/91565978-95175080-e975-11ea-95c0-0a8ed329d6fd.png)
替换了一下文件
![image](https://user-images.githubusercontent.com/70135780/91566406-356d7500-e976-11ea-9ebf-769ea144721b.png)
![image](https://user-images.githubusercontent.com/70135780/91565923-829d1700-e975-11ea-9d04-56afe47ea1b4.png)
速度感觉很不错
![image](https://user-images.githubusercontent.com/70135780/91566378-2686c280-e976-11ea-8e43-0d8126367567.png)
兼容性测试也完美过了
![image](https://user-images.githubusercontent.com/70135780/91566436-43bb9100-e976-11ea-97e4-6f7aded7b5ec.png)
就有点想不通为什么GPU比CPU兼容的多，但是GPU不支持而CPU支持。。。
![image](https://user-images.githubusercontent.com/70135780/91566655-909f6780-e976-11ea-8605-bbc6841f095e.png)
![image](https://user-images.githubusercontent.com/70135780/91566737-b0369000-e976-11ea-8a33-80b86536fb64.png)

**Comment by TianZerL** [comment]
这个兼容性不准吧，HD4000硬件只支持到OpenCL 1.1（1.2都是后来驱动加的），CPU的话毕竟是模拟支持，Intel愿意想支持到多少都可以👀。

**Comment by wwsq1149** [comment]
阿这
好吧能用就好
谢谢~
