### ISSUE TITLE
Compiling error on Ubuntu 19.10: cannot convert 'double' to 'cv::Size'

### ISSUE THREAD

**Issue by k4yt3x** [TianZerL/Anime4KCPP#41]
## Abstract

I'm trying to build a new Docker image for Video2X with Anime4KCPP added into the mix, but I quickly ran into some issues that I couldn't solve after some Googling and fiddling around. I'm by all means no C/CPP expert, so I decided to make a post here. I hope I'm not getting this error due to my stupid negligence somewhere. asciinema cast file is attached at the bottom for easy playback.

Thank you for your work and your time.

## Description

`cmake` runs successfully without problems, but when the program gets compiled with `make -j32`, it trips over several references to `fps` which should be converted to `cv::Size` ('cv::Size_<int>'). Below is one of the errors as an example.

```console
anime4kcpp/Anime4KCore/src/VideoIO.cpp: In member function 'bool Anime4KCPP::VideoIO::openWriter(const string&, Anime4KCPP::CODEC, const Size&, double)':
/anime4kcpp/Anime4KCore/src/VideoIO.cpp:76:91: error: cannot convert 'double' to 'cv::Size' {aka 'cv::Size_<int>'}
   76 |         writer.open(dstFile, cv::CAP_FFMPEG, cv::VideoWriter::fourcc('m', 'p', '4', 'v'), fps, size);
      |                                                                                           ^~~
      |                                                                                           |
      |                                                                                           double
```

The following is a screenshot just in case the code block isn't convenient to look at.

![image](https://user-images.githubusercontent.com/21986859/92048134-74d10280-ed76-11ea-9d7c-3f3ea1efb2ea.png)

## Build Script

Below is the section in the script I used to build Anime4KCPP.

```bash
# install the latest cmake for compiling Anime4KCPP
aria2c https://github.com/Kitware/CMake/releases/download/v3.18.2/cmake-3.18.2-Linux-x86_64.sh -o "$TEMP/cmake.sh"
mkdir /cmake
bash "$TEMP/cmake.sh" --prefix=/cmake --skip-license

# install Anime4KCPP
apt-fast install -y --no-install-recommends libopencv-dev opencl-dev libqt5svg5-dev qttools5-dev
git clone --recurse-submodules --depth=1 --progress https://github.com/TianZerL/Anime4KCPP.git $TEMP/anime4kcpp
mkdir -v $TEMP/anime4kcpp/build
cd $TEMP/anime4kcpp/build
/cmake/bin/cmake -DBuild_GUI=OFF ..
make -j$(nproc)
mv -v $TEMP/anime4kcpp/build $INSTALLATION_PATH/video2x/src/dependencies/anime4kcpp
mv -v $TEMP/anime4kcpp/models_rgb $INSTALLATION_PATH/video2x/src/dependencies/anime4kcpp/models_rgb
```
## Building From Release

To verify that this issue also applies to the releases, I tried compiling from the latest (2.3.0) release. However, cmake fails on a SHA1 hash check for some reason. I don't think it's worth it for me to investigate it further so here's the screenshot attached.

![image](https://user-images.githubusercontent.com/21986859/92047995-1b68d380-ed76-11ea-9fbf-1f57ad611132.png)

## Appendix

I have also attached the asciinema cast file and the full log file with this issue. You can play it back to see the exact build process in real time. Sorry I had to ZIP them since GitHub doesn't accept the file formats provided.

[anime4kcpp_build.zip](https://github.com/TianZerL/Anime4KCPP/files/5165397/anime4kcpp_build.zip)

**Comment by TianZerL** [comment]
OpenCV 4 is needed, I guess you are using OpenCV3 (directly install from ubuntu by apt-get). And for newest Anime4KCPP, I have updated the [cmdline](https://github.com/TianZerL/cmdline), that's why hash code changed.

**Comment by k4yt3x** [comment]
Thanks for the reply. I'll try compiling it with OpenCV 4.4.

**Comment by TianZerL** [comment]
OpenCV4.2.0 is already available in Ubuntu's official library.  
And I also committed an update to allow Anime4KCPP to compile on OpenCV3.

**Comment by k4yt3x** [comment]
> And I also committed an update to allow Anime4KCPP to compile on OpenCV3.

Fantastic. I'll try it right now.

**Comment by k4yt3x** [comment]
Beautiful. Much appreciated for the assistance.

![image](https://user-images.githubusercontent.com/21986859/92262525-cf7b7300-eeca-11ea-9f58-9bfddb78be52.png)

**Comment by TianZerL** [comment]
BTW, qt (libqt5svg5-dev qttools5-dev) is not needed for building cli only.

**Comment by k4yt3x** [comment]
Oh thanks for pointing that out. I copy-pasted that from a v2x thread.
