### ISSUE TITLE
CMake Error at cmake/ThirdPartyForGUI.cmake:1 (find_package)

### ISSUE THREAD

**Issue by arupakafreemail** [TianZerL/Anime4KCPP#43]
Hi Author,

I'm on macOS Catalina and followed all instructions, and now trying to install the cmake GUI with the command `cmake -DCMAKE_C_COMPILER="/usr/local/opt/llvm/bin/clang" -DCMAKE_CXX_COMPILER="/usr/local/opt/llvm/bin/clang++" .`. However, the following error occured:

`Demos-MacBook-Pro:Anime4KCPP-2 demo$  cmake -DCMAKE_C_COMPILER="/usr/local/opt/llvm/bin/clang" -DCMAKE_CXX_COMPILER="/usr/local/opt/llvm/bin/clang++" .
-- 
No CMAKE_BUILD_TYPE selected, defaulting to Release

CMake Error at cmake/ThirdPartyForGUI.cmake:1 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  GUI/CMakeLists.txt:37 (include)

-- Configuring incomplete, errors occurred!
See also "/Users/demo/Anime4KCPP-2/CMakeFiles/CMakeOutput.log".
See also "/Users/demo/Anime4KCPP-2/CMakeFiles/CMakeError.log".
Demos-MacBook-Pro:Anime4KCPP-2 demo$ `

Please let me know if I've missed any steps or if any further information is needed to solve the issue.

Thanks in advance!

Regards,
Arupaka

**Comment by TianZerL** [comment]
You need install Qt5 first, see [wiki](https://github.com/TianZerL/Anime4KCPP/wiki/Building#building-on-macos-from-nightmachinary)

**Comment by arupakafreemail** [comment]
Hi TianZerL,

Thank you so much for your prompt reply.

I believe I've installed Qt5 already by verifying with brew info qt and as the following image:
<img width="1440" alt="Screen Shot 2020-09-14 at 5 34 33 PM" src="https://user-images.githubusercontent.com/71255614/93069942-d7989700-f6b0-11ea-8c0f-b06a14e6c852.png">

I've also added it to environment variable as the following:
<img width="1440" alt="Screen Shot 2020-09-14 at 5 34 53 PM" src="https://user-images.githubusercontent.com/71255614/93070010-ec752a80-f6b0-11ea-926a-5156c3bdf877.png">

However, as I run the line `cmake -DCMAKE_C_COMPILER="/usr/local/opt/llvm/bin/clang" -DCMAKE_CXX_COMPILER="/usr/local/opt/llvm/bin/clang++" .` it still gives me the same error as below:
<img width="1440" alt="Screen Shot 2020-09-14 at 5 35 04 PM" src="https://user-images.githubusercontent.com/71255614/93070104-09116280-f6b1-11ea-9cf4-cde234d9c35a.png">

Did I install the Qt5 wrongly or missed any steps? Thank you!

**Comment by TianZerL** [comment]
Try
```
cmake -DCMAKE_C_COMPILER="/usr/local/opt/llvm/bin/clang" -DCMAKE_CXX_COMPILER="/usr/local/opt/llvm/bin/clang++" -DQt5_DIR="/usr/local/opt/qt/lib/cmake/Qt5" ..
```

**Comment by arupakafreemail** [comment]
Hi TianZerL,

Thanks again for your prompt reply.

I've just gave it a try with your line of code `cmake -DCMAKE_C_COMPILER="/usr/local/opt/llvm/bin/clang" -DCMAKE_CXX_COMPILER="/usr/local/opt/llvm/bin/clang++" -DQt5_DIR="/usr/local/opt/qt/lib/cmake/Qt5"` and it successfully compiled without error! (Thanks!!!)
<img width="1440" alt="Screen Shot 2020-09-14 at 5 59 26 PM" src="https://user-images.githubusercontent.com/71255614/93072597-2e53a000-f6b4-11ea-9694-f07ce2a94f86.png">

I've then ran `make` and believe that Anime4KCPP_GUI has been successfully installed (?):
<img width="401" alt="Screen Shot 2020-09-14 at 5 56 41 PM" src="https://user-images.githubusercontent.com/71255614/93072700-593df400-f6b4-11ea-9b0c-f1965e77954a.png">

If it is in fact successfully installed, I wonder how am I supposed to open the GUI...... sorry for such a stupid question, I'm a complete newbie to this lol.

Thanks in advance!

**Comment by TianZerL** [comment]
Your GUI executable file is in the `bin` folder in your CMake build build folder, just double click it to open it.

**Comment by arupakafreemail** [comment]
I MADE IT TianZerL!!!!!
<img width="1440" alt="Screen Shot 2020-09-14 at 6 19 31 PM" src="https://user-images.githubusercontent.com/71255614/93074400-e2562a80-f6b6-11ea-9ac6-8d815f15a551.png">

Thank you so much for your help and for your time!!!!! Wish you and Anime4KCPP all the best!!! hahaa

Please have a good day!!!

Regards,
Arupaka
