### ISSUE TITLE
Add support for directory of photos with Threads CLI option

### ISSUE THREAD

**Issue by donicrosby** [TianZerL/Anime4KCPP#44]
Is is possible to add threading support for a directory of photos similar to how you can do with videos?

Currently if I wanted to bulk process a lot of photos I would have to script it in order to use the CLI, being able to point the CLI at a directory and having it behave similarly to processing a video would be helpful for any sort of bulk processing.

**Comment by TianZerL** [comment]
Multithreading support for directory processing of the CLI has been added to the master branch.
