### ISSUE TITLE
A path issue with GUI

### ISSUE THREAD

**Issue by LianhuanJ** [TianZerL/Anime4KCPP#49]
If file path contains Unicode, the program returns error message
![image](https://user-images.githubusercontent.com/44343440/101262092-e3a76880-3776-11eb-83eb-caf8856db548.png)

**Comment by TianZerL** [comment]
Could you please provide an example? I tested it with Chinese, there are no issues.

**Comment by LianhuanJ** [comment]
> Could you please provide an example? I tested it with Chinese, there are no issues.
From your reply I noticed it might be the character encoding problem,
I then assume maybe you are using GBK encoding.

Here I take Traditional Chinese as example:
![image](https://user-images.githubusercontent.com/44343440/101273415-40833d00-37d0-11eb-95e8-6a68eb75a44d.png)

BTW below is py-api version also encountering same issue with Japanese path:
![image](https://user-images.githubusercontent.com/44343440/101273397-f8641a80-37cf-11eb-82f8-88344b12bee7.png)

**Comment by TianZerL** [comment]
After testing, I couldn't reproduce the problem in GUI：
![issue](https://user-images.githubusercontent.com/41182852/101273662-77f2e900-37d2-11eb-9887-7b75048a34bf.PNG)

But in Python, I reproduce that problem, I will check it out.

**Comment by LianhuanJ** [comment]
> After testing, I couldn't reproduce the problem in GUI：
> ![issue](https://user-images.githubusercontent.com/41182852/101273662-77f2e900-37d2-11eb-9887-7b75048a34bf.PNG)

It turns out that's an obvious charactor encoding issue, try using other Unicode path rather then Chinese, such as Japanese or what, you can see the errors.

Anyway, your works are still great and awesome, keep it up !

**Comment by TianZerL** [comment]
What is the language of your system? For the GUI, I've converted the encoding to the system's default encoding(By QString::toLocal8Bit()). Normally, there should be no problem in a unicode system.

**Comment by TianZerL** [comment]
I have updated pyanime4k to 2.5.1 and tried to make it support the default local encoding of your system. Please update and help me test it.

**Comment by LianhuanJ** [comment]
> What is the language of your system? For the GUI, I've converted the encoding to the system's default encoding(By QString::toLocal8Bit()). Normally, there should be no problem in a unicode system.

Mine is pure english though, maybe it's not quite good idea to convert encoding to user's locale.

> I have updated pyanime4k to 2.5.1 and tried to make it support the default local encoding of your system. Please update and help me test it.

Nah, it doesn't help. An user may probably store the original Japanese or Chinese filename even his/her locale is not JP/ZH.

So ya, the issue is not solved yet 🤕

**Comment by TianZerL** [comment]
in Windows，I must convert it to user locale，because opencv doesnt support non-ASCII input. So a way to make it work is input default 
 encoding as 8bit data of Windows to opencv.

**Comment by LianhuanJ** [comment]
OK, got it, thx anyway

**Comment by TianZerL** [comment]
After some attempts, I think I have solved the problem, please help [test GUI](https://www.swisstransfer.com/d/abb4a4ec-6bd2-444b-9eed-4be6f94ae03c).

And for pyanime4k, please update to 2.5.2, and add `locale.setlocale(locale.LC_CTYPE, ".UTF-8")` before call pyanime4k API:
```python
from pyanime4k import upscale
import locale

locale.setlocale(locale.LC_CTYPE, ".UTF-8")

upscale.show_upscaled_image(source_path=r"F:\Temp\Anime4K\永久檔案.png")

```

**Comment by LianhuanJ** [comment]
> After some attempts, I think I have solved the problem, please help [test GUI](https://www.swisstransfer.com/d/abb4a4ec-6bd2-444b-9eed-4be6f94ae03c).

![image](https://user-images.githubusercontent.com/44343440/101373353-cc3bbd00-38e7-11eb-95d8-a77574cb8ed4.png)
something weird blew out, I don't have that thing though.

> And for pyanime4k, please update to 2.5.2, and add `locale.setlocale(locale.LC_CTYPE, ".UTF-8")` before call pyanime4k API:
> 
> ```python
> from pyanime4k import upscale
> import locale
> 
> locale.setlocale(locale.LC_CTYPE, ".UTF-8")
> 
> upscale.show_upscaled_image(source_path=r"F:\Temp\Anime4K\永久檔案.png")
> ```

![image](https://user-images.githubusercontent.com/44343440/101373056-7f57e680-38e7-11eb-9d2e-cbe1a7da738b.png)
Your code works here, congratulation !

**Comment by TianZerL** [comment]
> something weird blew out, I don't have that thing though.
Do all images have this problem? It seems that there is something wrong with the suffix name when writing the image. Maybe you can specify it as PNG or jpg in GUI setting.

**Comment by LianhuanJ** [comment]
> > something weird blew out, I don't have that thing though.
> 
> Do all images have this problem? It seems that there is something wrong with the suffix name when writing the image. Maybe you can specify it as PNG or jpg in GUI setting.

![image](https://user-images.githubusercontent.com/44343440/101376472-96003c80-38eb-11eb-8c62-1b387bfcdd8d.png)
Yes, every combination of filepath and suffix goes wrong

**Comment by TianZerL** [comment]
I'm sorry, it's a stupid mistake caused by carelessness, and I'll fix it soon😂

**Comment by LianhuanJ** [comment]
> I'm sorry, it's a stupid mistake caused by carelessness, and I'll fix it soon😂.
> This is the [revised version](https://www.swisstransfer.com/d/668686d1-8ad6-4139-bb75-63e22ecbb21e).

Cool, it works perfectly !
![image](https://user-images.githubusercontent.com/44343440/101386153-b930e900-38f7-11eb-9088-9205b055813c.png)

Thank for your patient work, salute !
