### ISSUE TITLE
Vapoursynth: Supported color format confusion.

### ISSUE THREAD

**Issue by Selur** [TianZerL/Anime4KCPP#52]
Before the last updates I assumed Anime4KCPP would:
a. always support RGB24
and
b. add YUV444P8 support when ACNet was enabled.

Now with https://github.com/TianZerL/Anime4KCPP/wiki/VapourSynth-plugin and  the changelog from https://github.com/TianZerL/Anime4KCPP/releases/tag/v2.5.0 I'm confused about what color formats are supported.

Could you please list what color formats are supported, with:
 (I guess: "Gray16, Gray8, Grays, RGB24, RGB48, RGBS, YUV444P8, YUV444P16, YUV444PS, YUV422P8, YUV420P16, YUV402P8, YUV420P16" are the potentially supported color formats.)
* "ACNet=0,safeMode=1": ?
* "ACNet=1,safeMode=1": ?
* "ACNet=0,safeMode=0": ?
* "ACNet=1,safeMode=0": ?

Thanks!

**Comment by TianZerL** [comment]
wiki is out of date. I haven't updated it yet.
Supported color format:
- "ACNet=0,safeMode=1", "ACNet=0,safeMode=0", "ACNet=1,safeMode=0" :
  - Gray8
  - Gray16
  - GrayS
  - RGB24
  - RGB48
  - RGBS
  - YUV444P8
  - YUV444P16
  - YUV444PS
 - "ACNet=1,safeMode=1":
   - Gray8
   - Gray16
   - GrayS
   - RGB24
   - RGB48
   - RGBS
   - YUV444P8
   - YUV444P16
   - YUV444PS
   - YUV422P8
   - YUV422P16
   - YUV422PS
   - YUV420P8
   - YUV420P16
   - YUV420PS

**Comment by Selur** [comment]
Thanks for clearing that up.  👍
