### ISSUE TITLE
Fail to run on arm64

### ISSUE THREAD

**Issue by ArdvarkDev** [TianZerL/Anime4KCPP#54]
No matter what I install, I just cannot get the program to run in video processing mode.
Error message:
Failed to load file: file doesn't not exist or decoder isn't installed

OS: Ubuntu 20.04.2 LTS aarch64

**Comment by TianZerL** [comment]
Make sure your opencv was fully compiled with ffmpeg module.

**Comment by ArdvarkDev** [comment]
Ah, that was it.
