### ISSUE TITLE
请教model怎么快速转成glsl？

### ISSUE THREAD

**Issue by FrankyCao** [TianZerL/Anime4KCPP#66]
model里面权重参数这么多，请教怎么快速转到glsl呢？复制粘贴效率较低

**Comment by TianZerL** [comment]
python之类的写脚本呗

**Comment by TianZerL** [comment]
(๑•̀ㅂ•́)و✧

**Comment by FrankyCao** [comment]
> (๑•̀ㅂ•́)و✧

ACNet用于真人效果对比fsrcnn会不会好点？楼主有用真人数据集训练过吗？

**Comment by TianZerL** [comment]
这个没试过，具体效果有待探究。

**Comment by FrankyCao** [comment]
> 这个没试过，具体效果有待探究。

所以什么时候有空探究一下？等你结果

**Comment by TianZerL** [comment]
我目前没有这个打算。

**Comment by FrankyCao** [comment]
> 我目前没有这个打算。

好吧，那你训练部分的代码有打算开源么？

**Comment by TianZerL** [comment]
可以开源，就是写的太乱，暂时懒得整理。需要的话gitee上有我之前整理的训练用的[代码](https://gitee.com/tianzerl/swjtu_waifu2x_fsrcnn)，但因为是课程用途的，没包含ACNet，可以自己根据网络结构加到[module.py](https://gitee.com/tianzerl/swjtu_waifu2x_fsrcnn/blob/master/module.py)里。

**Comment by FrankyCao** [comment]
> 可以开源，就是写的太乱，暂时懒得整理。需要的话gitee上有我之前整理的训练用的[代码](https://gitee.com/tianzerl/swjtu_waifu2x_fsrcnn)，但因为是课程用途的，没包含ACNet，可以自己根据网络结构加到[module.py](https://gitee.com/tianzerl/swjtu_waifu2x_fsrcnn/blob/master/module.py)里。



> 可以开源，就是写的太乱，暂时懒得整理。需要的话gitee上有我之前整理的训练用的[代码](https://gitee.com/tianzerl/swjtu_waifu2x_fsrcnn)，但因为是课程用途的，没包含ACNet，可以自己根据网络结构加到[module.py](https://gitee.com/tianzerl/swjtu_waifu2x_fsrcnn/blob/master/module.py)里。

👍好的，明天研究研究

**Comment by shigebendana** [comment]
> model里面权重参数这么多，请教怎么快速转到glsl呢？复制粘贴效率较低

hello，博主，请问你现在有什么相关教程可以推荐给我吗? 十分感谢
