### ISSUE TITLE
FFmpeg not found

### ISSUE THREAD

**Issue by dausruddin** [TianZerL/Anime4KCPP#68]
Hi. I am using Arch Linux and upon setting ffmpeg path within GUI, it says `FFmpeg not found`

I have ffmpeg installed
<kbd>![image](https://user-images.githubusercontent.com/5763466/120095149-eea3ea00-c156-11eb-8cae-de0a7eef9f33.png)</kbd>

Then I set the path
<kbd>![image](https://user-images.githubusercontent.com/5763466/120095160-febbc980-c156-11eb-9721-2f4b437549df.png)</kbd>

It then says FFmpeg not found
<kbd>![image](https://user-images.githubusercontent.com/5763466/120095169-0c714f00-c157-11eb-869d-b57c224b33b2.png)</kbd>

But somehow the program can run
```----------------------------------------------
           Welcome to Anime4KCPP GUI          
----------------------------------------------
         Anime4KCPP GUI v1.13.0                 
         Anime4KCPP Core v2.6.0                
----------------------------------------------
----------------------------------------------
             ----------------------------------------------
             FFmpeg check failed              
----------------------------------------------
FFmpeg path: "/usr/bin/ffmpeg"
              
----------------------------------------------
FFmpeg path: "ffmpeg"
----------------------------------------------
             FFmpeg check failed              
----------------------------------------------
FFmpeg path: "/usr/bin/ffmpeg"
2021-05-30T14:48:59.703  Video: /home/john/Downloads/video.mp4, start processing...```

So, I am not quite sure if this is a problem or not. Maybe a fix would be needed?

Thank you.

**Comment by TianZerL** [comment]
Did you compile with QT6?

**Comment by dausruddin** [comment]
QT5 as that is what mentioned in the wiki.

**Comment by TianZerL** [comment]
I will to do some tests in Manjaro KDE to reproduce the problem, will reply later. Can you provide QT version.

**Comment by dausruddin** [comment]
Thank you. The version is `5.15.2`

**Comment by TianZerL** [comment]
Already fixed. The problem is that Linux and windows escape paths in different ways. Before recompiling, remember to delete the old settings.ini.

**Comment by dausruddin** [comment]
Thank you! I can confirm that the issue is fixed.
