### ISSUE TITLE
PotPlayer - seems active, but no image difference

### ISSUE THREAD

**Issue by FluffyDiscord** [TianZerL/Anime4KCPP#73]
Hi, I don't think the DirectShow version works for me. Images look the same when I am comparing screenshots. Would you mind checking my settings?

![image](https://user-images.githubusercontent.com/10332247/124603249-03685180-de6a-11eb-83d0-1f5b19d9a3de.png)

![image](https://user-images.githubusercontent.com/10332247/124603120-e3d12900-de69-11eb-93bb-c5e3eff3cc77.png)

**Comment by TianZerL** [comment]
What is the player?

**Comment by FluffyDiscord** [comment]
Player - DirectShow PotPlayer. Disabling BFRC does not help.

**Comment by TianZerL** [comment]
How about the MPC-BE?

**Comment by TianZerL** [comment]
Well, I think that's because the 12bit video is not support yet, 8bit, 10bit or 16bit is wanted.

**Comment by FluffyDiscord** [comment]
> 
> 
> How about the MPC-BE?

Seems to work - default installation.

![image](https://user-images.githubusercontent.com/10332247/124605197-f51b3500-de6b-11eb-8aa3-1328d4cee1a5.png)

**Comment by TianZerL** [comment]
May I have the `Pin Info` page of the A4K DSFilter when you are playing the video?

**Comment by FluffyDiscord** [comment]
```python
Filter : Anime4KCPP for DirectShow - CLSID : {731AE2E9-EEED-4E29-B81B-5DC8A0D6A307}

- Connected to:

CLSID: {EE30215D-164F-4A92-A4EB-9D4C13390F9F}
Filter: LAV Video Decoder (internal)
Pin: Output

- Connection media type:

Video: NV12 1920x1080 23.976fps

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Video {73646976-0000-0010-8000-00AA00389B71}
subtype: MEDIASUBTYPE_NV12 {3231564E-0000-0010-8000-00AA00389B71}
formattype: FORMAT_VideoInfo2 {F72A76A0-EB0A-11D0-ACE4-0000C0CC16BA}
bFixedSizeSamples: 1
bTemporalCompression: 0
lSampleSize: 3110400
cbFormat: 112

VIDEOINFOHEADER:
rcSource: (0,0)-(1920,1080)
rcTarget: (0,0)-(1920,1080)
dwBitRate: 0
dwBitErrorRate: 0
AvgTimePerFrame: 417083

VIDEOINFOHEADER2:
dwInterlaceFlags: 0x00000000
dwCopyProtectFlags: 0x00000000
dwPictAspectRatioX: 16
dwPictAspectRatioY: 9
dwControlFlags: 0x00000000
dwReserved2: 0x00000000

BITMAPINFOHEADER:
biSize: 40
biWidth: 1920
biHeight: 1080
biPlanes: 1
biBitCount: 12
biCompression: NV12
biSizeImage: 3110400
biXPelsPerMeter: 0
biYPelsPerMeter: 0
biClrUsed: 0
biClrImportant: 0

pbFormat:
0000: 00 00 00 00 00 00 00 00 80 07 00 00 38 04 00 00 ...........8...
0010: 00 00 00 00 00 00 00 00 80 07 00 00 38 04 00 00 ...........8...
0020: 00 00 00 00 00 00 00 00 3b 5d 06 00 00 00 00 00 ........;]......
0030: 00 00 00 00 00 00 00 00 10 00 00 00 09 00 00 00 ................
0040: 00 00 00 00 00 00 00 00 28 00 00 00 80 07 00 00 ........(......
0050: 38 04 00 00 01 00 0c 00 4e 56 31 32 00 76 2f 00 8.......NV12.v/.
0060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
```

**Comment by FluffyDiscord** [comment]
> 
> 
> Well, I think that's because the 12bit video is not supported yet, 8bit, 10bit or 16bit is wanted.

Tried to play 10bit in PotPlayer and it failed to playback the video, only audio is coming out.

**Comment by TianZerL** [comment]
You need to make sure that the output of the decoder is one of the following:
YV12
NV12
IYUV(I420)
RGB24
RGB32
P010
P016

**Comment by TianZerL** [comment]
Can you provide a short video to test it?

**Comment by TianZerL** [comment]
Is 8bit video work for you? I just tested 8bit video and it's work. output size is for decoder, so it is normal that same with input size.
![image](https://user-images.githubusercontent.com/41182852/124608114-06326900-dea1-11eb-91de-a742a2ac18a5.png)

**Comment by FluffyDiscord** [comment]
Did a PotPlayer reset, it seems to make it work as long as it is 8,10 or 16 bit. 12bit crashes with this message:

![image](https://user-images.githubusercontent.com/10332247/124611809-17b04c80-de72-11eb-89ee-ccafcffc9beb.png)


The BFRC actually shows the incoming resolution and as it reports, it should work. Comparing the images from before and after, it does super sample the video. It's a bit sad, that it has to be AFTER the BFRC interpolates the video and not before, but I guess I will have to live with it.

![image](https://user-images.githubusercontent.com/10332247/124610301-af14a000-de70-11eb-9b5a-44740e968e12.png)

The main issue is the 12bit support. Also can I change upsample Anime4K algorithm ? Comparing 480p DVD rip with this filter and madVR, the madVR looks superior.

**Comment by TianZerL** [comment]
From your screenshot, Anime4KCPP DSFilter does work before BFRC, which is the way I recommend.

If performance is not a problem, madVR may be a better choice.    

12bit video support may not be available in a short time, and there are few Anime videos in this format.

**Comment by FluffyDiscord** [comment]
Sorry to reopen - it's failing for 8bit files with that kernelbase.dll exception.

![image](https://user-images.githubusercontent.com/10332247/124619767-382fd500-de79-11eb-8106-d31e4b987500.png)

playback without the filter

![image](https://user-images.githubusercontent.com/10332247/124619962-5d244800-de79-11eb-9614-df50cddbe683.png)

do you need the sample file ?

**Comment by TianZerL** [comment]
> do you need the sample file ?

Yes

**Comment by TianZerL** [comment]
kernelbase.dll exception, as far as I know, occurs when the filter parameters are changed by settings page while the video is playing.

**Comment by FluffyDiscord** [comment]
> 
> 
> kernelbase.dll exception, as far as I know, occurs when the filter parameters are changed by settings page while the video is playing.

That's weird. I don't change parameters. Maybe the PotPlayer does when starting up for some reason. [There's the file](https://mega.nz/file/V8JHDYoZ#tL9wV7NiW6qmarsCsaEuYdlSWs_xPhOyaAYJ0oiqgVk)

**Comment by TianZerL** [comment]
if open a4k setting page from potplayer settings when video is playing, it will occur when you press ok button even you dont change anything. You can open a4k setting page by right click menu to avoid it.

I will test the file tomorrow. It's time to go to bed now in local time.💤

**Comment by TianZerL** [comment]
I tested your file, it works. I think the reason for not working has something to do with BRFC, they are not compatible with certain formats of video.

**Comment by FluffyDiscord** [comment]
Thing is, the error shows up even when BFRC is off.

**Comment by TianZerL** [comment]
My PotPlayer settings is all default, just add Anime4KCPP Filter.

**Comment by FluffyDiscord** [comment]
While opening the file.

I had to uncheck 8bit 4:2:0 from lav video decoder. Now it forces decoding in 10bit and works properly.

The incompatibility between BFRC and Anime4kCPP is still mystery to me as some files play normally and some not, regardless if it's 8, 10 or 12bit or h264 or hevc. Some encoding options are not supported I guess. Reencoding videos with ffmpeg to h264 10bit makes them playable with both filters, where before they would error out on opening and I could use only one of them.

**Comment by TianZerL** [comment]
That's weird, I tried MPC-HC with LAV decoder, it works properly. I'm not sure if this is a compatibility issue with potplayer or a specific version of LAV.
![image](https://user-images.githubusercontent.com/41182852/124872068-62a79c80-dff7-11eb-874d-c26969e7f276.png)

The compatibility between BFRC and Anime4KCPP is not only affected by the video format, but also by the GPU. For example, my Vega8 can't play any video higher than 480p with both BFRC and Anime4KCPP. Therefore, it is difficult for me to give a specific explanation of compatibility.

**Comment by FluffyDiscord** [comment]
Does my strack trace log say anything ?

I have confirmed that I can play 1080p 24/25/30fps video with Anime4kCPP and BFRC once I re-encode anime to 10bit (first thing I tried and worked)

```
ffmpeg -i input.mkv -c:v libx264 -crf 16 -pix_fmt yuv420p10le -c:a copy -map 0 output_10bit.mkv
```

I have contacted BFRC about this and he said that the issue is on this plugin side, as his exception stack trace also ends up with at the Anime4kCPP side.

```
Anime4KCPP::ACException<Anime4KCPP::ExceptionType::GPU,1>0x0000004EDC2FEC48
```

**Comment by TianZerL** [comment]
it crashed in a function that called OpenCL to execute kernel, I want to know:  
- Does mpc-be have this crash problem?
- Is it helpful to turn off  `OpenCL parallel IO`?

**Comment by TianZerL** [comment]
You can also try this new version
[Anime4KCPP_DSFilter.zip](https://github.com/TianZerL/Anime4KCPP/files/6794490/Anime4KCPP_DSFilter.zip)

**Comment by FluffyDiscord** [comment]
Using the test file from this thread I set the output formats to your recommended settings.

BFRC setttings

![image](https://user-images.githubusercontent.com/10332247/125156874-1cbe1600-e168-11eb-9b54-2d8132dfec65.png)

on error

![image](https://user-images.githubusercontent.com/10332247/125156911-49722d80-e168-11eb-8d8a-68e430f60959.png)


LAV Video decoder

![image](https://user-images.githubusercontent.com/10332247/125156899-365f5d80-e168-11eb-926a-5dab57e72c71.png)

Anime4K error

![image](https://user-images.githubusercontent.com/10332247/125156930-555def80-e168-11eb-9759-b9f2973437e9.png)

clicking on ok eventually let's the video play with green color (corrupted) and sound, 1 click = ~1s

![image](https://user-images.githubusercontent.com/10332247/125156973-92c27d00-e168-11eb-954f-6412cc788ac5.png)

pausing the video and checking the potplayer playback

![image](https://user-images.githubusercontent.com/10332247/125157637-7d4f5200-e16c-11eb-80f9-5ded6b4f42bd.png)

cpp settings

![image](https://user-images.githubusercontent.com/10332247/125157650-8cce9b00-e16c-11eb-91f0-f1917ea44f55.png)

error log - not sure if it's for the test cpp version from this thread or the release version one (modified time seems too old)

[Log.zip](https://github.com/TianZerL/Anime4KCPP/files/6794933/Log.zip)

-----------------

Now, quick re-encoding the test video [download here](https://mega.nz/file/pkAzEQBZ#43ZaAmjq69zSChXpUP31KnsK4rrpsd5CVPuwjvtdHUs) to `yuv420p` using 
```
ffmpeg.exe -i "[Erai-raws] Akudama Drive - 09 [1080p].mkv" -c:v h264_amf -profile high -quality speed -qp_i 16 -qp_p 16 -qp_b 16 -coder cabac -pix_fmt yuv420p -map 0 -c:a copy test.mkv
```

allows me to play the file with both filters.

Same settings as before - lav video decoder seems to decode to nv12

![image](https://user-images.githubusercontent.com/10332247/125158420-521b3180-e171-11eb-8b7a-9e8072c8b85a.png)

**Comment by TianZerL** [comment]
Thank you very much for your detailed test.   

I tried to test the problem with vega8. According to the error message of anime4kcpp, the cause of the error is an error in creating OpenCL kernel. I think it may be caused by the performance of graphics card or OpenCL driver. On vega8, the problem is even more serious. Only 480p video can turn on two filters at the same time. After disabling BFRC, 1080p and 720p videos can be played correctly.

And the video format may also affect the playback. I think the crash of the test video may be caused by the frame rate. There are some differences between the payback frame rate (23976/1000, it's a weird valued, usually we just use 24000/1001, although they are the same in theory, the player's handling may be different) and the original frame rate(24000/1001) of the test video. And the re-encode one has only one frame rate(24000/1001).

Changing the output format or video transcoding can solve the crash caused by the format. But when the performance of GPU is insufficient, this problem will certainly happen. Unfortunately, I don't have a good solution to this problem.

**Comment by FluffyDiscord** [comment]
I guess there's nothing you can do.

We could also try how GCN 5 gpu behaves, like Radeon RX Vega 56/64, as it has newer hw decoder, but I know nobody with that gpu. They we could probably confirm, that it is indeed hw limitation.

Thank you for your time.
