### ISSUE TITLE
Ignore GUI blank output folder selection

### ISSUE THREAD

**Issue by k4yt3x** [TianZerL/Anime4KCPP#8]
Maybe consider not to overwrite the current output path when no folder is selected.
The file select function will return an empty string (at least PyQt5) if no folder is selected. Ignore and return if it is empty.

![image](https://user-images.githubusercontent.com/21986859/81304321-701c6c00-906c-11ea-8b51-91350c77d7d7.png)

**Comment by TianZerL** [comment]
It is safe that `output path` is empty. Files will be output to a sub folder  `output`  in the Anime4KCPP's folder. And if the target folder of `output path` does not exists, it will be created automatically.

**Comment by k4yt3x** [comment]
What I mean is if you click the "pick" button, close the file explorer dialog without selecting anything, it will still wipe out the line in output path.

**Comment by TianZerL** [comment]
Well, I see. It will be fixed.

**Comment by TianZerL** [comment]
This has been fixed.
