### ISSUE TITLE
error: (-215:Assertion failed) mv[i].size == mv[0].size && mv[i].depth() == depth in function 'cv::merge'

### ISSUE THREAD

**Issue by seiya-git** [TianZerL/Anime4KCPP#83]
Some images with preserving alpha cannot be resized if zoom factor is double

command:
```
Anime4KCPP_CLI --CNNMode --HDN --HDNLevel 1 --zoomFactor 1.75 --alpha --GPUMode --GPGPUModel cuda -i "test.png"
```

error:
`
OpenCV(4.5.0) C:\build\master_winpack-build-win64-vc15\opencv\modules\core\src\merge.dispatch.cpp:129: error: (-215:Assertion failed) mv[i].size == mv[0].size && mv[i].depth() == depth in function 'cv::merge'
`

Test image:
[test.png](https://user-images.githubusercontent.com/7394323/141611035-dfd7ebb1-43fd-4b1c-bed5-5b4c80853e48.png)

**Comment by TianZerL** [comment]
Resolved in master branch
