### ISSUE TITLE
compile error gui

### ISSUE THREAD

**Issue by geosone** [TianZerL/Anime4KCPP#87]
when compiling git from git i get this error on compile with gui support.

/home/mario/upscale/Anime4KCPP/GUI/src/mainwindow.cpp:1314:43: Fehler: »sleep_for« ist kein Element von »std::this_thread«
 1314 |                         std::this_thread::sleep_for(std::chrono::milliseconds(1000));
      |                                           ^~~~~~~~~
make[2]: *** [GUI/CMakeFiles/Anime4KCPP_GUI.dir/build.make:180: GUI/CMakeFiles/Anime4KCPP_GUI.dir/src/mainwindow.cpp.o] Fehler 1
make[2]: Verzeichnis „/home/mario/upscale/Anime4KCPP/build“ wird verlassen
make[1]: *** [CMakeFiles/Makefile2:255: GUI/CMakeFiles/Anime4KCPP_GUI.dir/all] Fehler 2
make[1]: Verzeichnis „/home/mario/upscale/Anime4KCPP/build“ wird verlassen
make: *** [Makefile:139: all] Fehler 2

**Comment by TianZerL** [comment]
Please post your compiler name and version.

**Comment by geosone** [comment]
cpp (Gentoo 11.2.0 p1) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
Dies ist freie Software; die Kopierbedingungen stehen in den Quellen. Es
gibt KEINE Garantie; auch nicht für MARKTGÄNGIGKEIT oder FÜR SPEZIELLE ZWECKE.

**Comment by TianZerL** [comment]
G++? Anyway, first try to see if the latest commit can be compiled.

**Comment by geosone** [comment]
the pull from now compiles.
