### ISSUE TITLE
MPC-BE加载后音画不同步

### ISSUE THREAD

**Issue by snhun** [TianZerL/Anime4KCPP#91]
开启前
![不问天1](https://user-images.githubusercontent.com/5186603/165545675-e4fc58c3-43f8-4ef6-a9e2-07f241c6305c.png)
开启后
![不问天2](https://user-images.githubusercontent.com/5186603/165545726-52808468-f8b9-4519-a168-d9b87201d8d4.png)

音画不同步，有丢帧，还出现过一次崩溃。

视频是B站下载测试的

**Comment by TianZerL** [comment]
帧数不足导致的，满速24帧，开启后只有16帧，当前设置下性能应该不太够。

**Comment by snhun** [comment]
> 帧数不足导致的，满速24帧，开启后只有16帧，当前设置下性能应该不太够。满速实时1080P超4K的话，N卡至少需要 GTX1060，A卡需要RX470。

用MPV测试，1080超4K+动态补针都非常流畅，应该不至于性能不够吧。

![QQ截图20220501134211](https://user-images.githubusercontent.com/5186603/166133804-e0c4a41e-b3f5-457c-a3d7-abfb470c012c.png)

**Comment by TianZerL** [comment]
MPV使用shader运算性能要求更低，因为不用把数据从内存到显存倒来倒去。GTX960用ACNetGLSL也是没有问题的。

**Comment by snhun** [comment]
> MPV使用shader运算性能要求更低，因为不用把数据从内存到显存倒来倒去。瓶颈不在算力，而在带宽上与显存速度上。GTX960用ACNetGLSL也是没有问题的。

了解，多谢解答！
