### ISSUE TITLE
cmake cli linux hash mismatch

### ISSUE THREAD

**Issue by MrComexs** [TianZerL/Anime4KCPP#93]
This is the output. I not sure if I did something wrong.

Artix:[comexs]:~$ cmake ~/Desktop/Anime4KCPP-2.5.0/
-- C++ compiler flags:
 -fopenmp -lpthread
-- Building information:
   Build CLI ON
   Build GUI OFF
   Build VapourSynth plugin OFF
   Build AviSynthPlus plugin OFF
   Build C wrapper OFF

   Build C wrapper with core OFF
   Built-in kernel ON

   Use Boost filesystem OFF
   Use TBB OFF
   Enable CUDA OFF

Warning:
   Local SHA1 for comline.h:   da39a3ee5e6b4b0d3255bfef95601890afd80709
   Expected SHA1:              383044e4fbc6066249d4102a39431d67ed3657c7
   Mismatch SHA1 for cmdline.h, trying to download it...
CMake Error at cmake/ThirdPartyForCLI.cmake:13 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/comexs/Desktop/Anime4KCPP-2.5.0/ThirdParty/include/cmdline.h]
      expected hash: [383044e4fbc6066249d4102a39431d67ed3657c7]
        actual hash: [da39a3ee5e6b4b0d3255bfef95601890afd80709]
             status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
  CLI/CMakeLists.txt:23 (include)

-- Configuring incomplete, errors occurred!
See also "/home/comexs/CMakeFiles/CMakeOutput.log".

**Comment by TianZerL** [comment]
I suggest you build the lasted git version, `cmdline.h` is already updated.

You can manually download the `cmdline.h` for v2.5.0 [here](https://raw.githubusercontent.com/TianZerL/cmdline/98ec5a291ce824ba6315537ae13e81a45d374e7c/cmdline.h), and put it in `/home/comexs/Desktop/Anime4KCPP-2.5.0/ThirdParty/include/`

**Comment by MrComexs** [comment]
Okay so I replace the cmdline but this happend. Sorry I'm new to doing this

Artix:[comexs]:~/Desktop/Anime4KCPP-2.5.0$ cmake ~/Desktop/Anime4KCPP-2.5.0/
-- The C compiler identification is GNU 12.1.0
-- The CXX compiler identification is GNU 12.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Failed to complie has_filesystem.cpp, will use boost::filesystem instead of std::filesystem

-- C++ compiler flags:
 -fopenmp -lpthread
-- Building information:
   Build CLI ON
   Build GUI OFF
   Build VapourSynth plugin OFF
   Build AviSynthPlus plugin OFF
   Build C wrapper OFF

   Build C wrapper with core OFF
   Built-in kernel ON

   Use Boost filesystem ON
   Use TBB OFF
   Enable CUDA OFF

-- Found OpenCV: /usr (found version "4.6.0") 
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - found
-- Found OpenCL: /usr/lib/libOpenCL.so (found version "2.2") 
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR filesystem)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindBoost.cmake:2376 (find_package_handle_standard_args)
  cmake/ThirdPartyForCLI.cmake:35 (find_package)
  CLI/CMakeLists.txt:23 (include)


-- Configuring incomplete, errors occurred!
See also "/home/comexs/Desktop/Anime4KCPP-2.5.0/CMakeFiles/CMakeOutput.log".

**Comment by TianZerL** [comment]
Ture `Boost filesystem` off with `-DUse_Boost_filesystem=OFF`.

**Comment by MrComexs** [comment]
cool it worked.
