### ISSUE TITLE
GUI在QT5.12上编译错误

### ISSUE THREAD

**Issue by FantasyGmm** [TianZerL/Anime4KCPP#95]
出错错误文件为 https://github.com/TianZerL/Anime4KCPP/blob/master/GUI/src/mainwindow.cpp 1463行
5.14之后的版本的写法才是`Qt::SkipEmptyParts`，所以5.12上会报错
需要改为
```
#if (QT_VERSION <= QT_VERSION_CHECK(5,14,0))
        split(',', QString::SkipEmptyParts).
#else
        split(',', Qt::SkipEmptyParts).
#endif
```
该部分参照上方726-732的宏定义

**Comment by TianZerL** [comment]
PR吧
