### ISSUE TITLE
Question to compare waifu2x and anime4k

### ISSUE THREAD

**Issue by Daijobou** [TianZerL/Anime4KCPP#99]
Wow... this two algorithm are insane. I compiled anime4kcpp on ubuntu with windows 11 (wsl) and compared it with waifu2x.
Waifu2x its a little bit better (sharper, more details), so I wonder, is there a way for better output with anime4k or in this case waifu2x is a little bit better?

Original Test-Image (width:200px)
![image](https://user-images.githubusercontent.com/260343/187990726-5acecb83-868c-455c-9a44-e5e1960d33ed.png)

anime4k with options -w -L 1
![image](https://user-images.githubusercontent.com/260343/187990969-e9eda026-1f27-4d7a-afcd-01fe1cb4db55.png)

Waifu2x (created from [website](http://waifu2x.udp.jp/index.html))
![image](https://user-images.githubusercontent.com/260343/187991139-6c84dfa4-ab6f-49b4-b630-466514f8ff4d.png)

Maybe you miss the differences, here marked with red. Waifu2x show more details. Anime4k is a little blurred.
![image](https://user-images.githubusercontent.com/260343/187992177-b3caa81d-f4fb-4f52-b511-d33734e71934.png)

I don't see any option to improve the quality further. Am I missing something? I don't have a GPU.
Can anyone help me out here? Thanks! :)

And one more question.
Here https://github.com/TianZerL/Anime4KCPP#result is right side a "Origin HR" image. What this means? Where does that come from? I don't see any setting for this.

**Comment by TianZerL** [comment]
It is expected that Anime4KCPP is not as good as Waifu2X. The former aims at real-time processing, which means that the amount of CNN's parameters is much less. If you want to get a high-quality single image, I would suggest you use Waifu2X or more complicated algorithm.
`Origin HR` literally means "Origin High Resolution Image", it's the the target of processing.

**Comment by TianZerL** [comment]
If you want sharper image, don't enable HDN (without '-L' option). Excessive noise reduction will make the image lack of detail.
And I will recommend you [waifu2x-ncnn-vulkan](https://github.com/nihui/waifu2x-ncnn-vulkan) for single anime image processing.
